/* mapwidget.c generated by valac 0.56.18, the Vala compiler
 * generated from mapwidget.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <shumate/shumate.h>
#include <glib.h>
#include <float.h>
#include <math.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define KCTRACKER_TYPE_MAPWIDGET (kctracker_mapwidget_get_type ())
#define KCTRACKER_MAPWIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KCTRACKER_TYPE_MAPWIDGET, KctrackerMapwidget))
#define KCTRACKER_MAPWIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KCTRACKER_TYPE_MAPWIDGET, KctrackerMapwidgetClass))
#define KCTRACKER_IS_MAPWIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KCTRACKER_TYPE_MAPWIDGET))
#define KCTRACKER_IS_MAPWIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KCTRACKER_TYPE_MAPWIDGET))
#define KCTRACKER_MAPWIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KCTRACKER_TYPE_MAPWIDGET, KctrackerMapwidgetClass))

typedef struct _KctrackerMapwidget KctrackerMapwidget;
typedef struct _KctrackerMapwidgetClass KctrackerMapwidgetClass;
typedef struct _KctrackerMapwidgetPrivate KctrackerMapwidgetPrivate;
enum  {
	KCTRACKER_MAPWIDGET_0_PROPERTY,
	KCTRACKER_MAPWIDGET_NUM_PROPERTIES
};
static GParamSpec* kctracker_mapwidget_properties[KCTRACKER_MAPWIDGET_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define KCTRACKER_TYPE_MARKERMAKER (kctracker_markermaker_get_type ())
#define KCTRACKER_MARKERMAKER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KCTRACKER_TYPE_MARKERMAKER, KctrackerMarkermaker))
#define KCTRACKER_MARKERMAKER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KCTRACKER_TYPE_MARKERMAKER, KctrackerMarkermakerClass))
#define KCTRACKER_IS_MARKERMAKER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KCTRACKER_TYPE_MARKERMAKER))
#define KCTRACKER_IS_MARKERMAKER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KCTRACKER_TYPE_MARKERMAKER))
#define KCTRACKER_MARKERMAKER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KCTRACKER_TYPE_MARKERMAKER, KctrackerMarkermakerClass))

typedef struct _KctrackerMarkermaker KctrackerMarkermaker;
typedef struct _KctrackerMarkermakerClass KctrackerMarkermakerClass;
#define _kctracker_markermaker_unref0(var) ((var == NULL) ? NULL : (var = (kctracker_markermaker_unref (var), NULL)))
#define _g_array_unref0(var) ((var == NULL) ? NULL : (var = (g_array_unref (var), NULL)))

struct _KctrackerMapwidget {
	GtkBox parent_instance;
	KctrackerMapwidgetPrivate * priv;
	ShumateSimpleMap* shumateMap;
	ShumateMarkerLayer* viewportLayer;
	ShumateRasterRenderer* rasterRenderer;
};

struct _KctrackerMapwidgetClass {
	GtkBoxClass parent_class;
};

static gpointer kctracker_mapwidget_parent_class = NULL;

VALA_EXTERN GType kctracker_mapwidget_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KctrackerMapwidget, g_object_unref)
VALA_EXTERN KctrackerMapwidget* kctracker_mapwidget_new (void);
VALA_EXTERN KctrackerMapwidget* kctracker_mapwidget_construct (GType object_type);
static GObject * kctracker_mapwidget_constructor (GType type,
                                           guint n_construct_properties,
                                           GObjectConstructParam * construct_properties);
VALA_EXTERN gpointer kctracker_markermaker_ref (gpointer instance);
VALA_EXTERN void kctracker_markermaker_unref (gpointer instance);
VALA_EXTERN GParamSpec* kctracker_param_spec_markermaker (const gchar* name,
                                              const gchar* nick,
                                              const gchar* blurb,
                                              GType object_type,
                                              GParamFlags flags);
VALA_EXTERN void kctracker_value_set_markermaker (GValue* value,
                                      gpointer v_object);
VALA_EXTERN void kctracker_value_take_markermaker (GValue* value,
                                       gpointer v_object);
VALA_EXTERN gpointer kctracker_value_get_markermaker (const GValue* value);
VALA_EXTERN GType kctracker_markermaker_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KctrackerMarkermaker, kctracker_markermaker_unref)
VALA_EXTERN KctrackerMarkermaker* kctracker_markermaker_new (void);
VALA_EXTERN KctrackerMarkermaker* kctracker_markermaker_construct (GType object_type);
VALA_EXTERN GArray* kctracker_markermaker_marker_compiler (KctrackerMarkermaker* self,
                                               GError** error);
static void kctracker_mapwidget_finalize (GObject * obj);
static GType kctracker_mapwidget_get_type_once (void);

KctrackerMapwidget*
kctracker_mapwidget_construct (GType object_type)
{
	KctrackerMapwidget * self = NULL;
#line 1 "../src/gtk/mapwidget.vala"
	self = (KctrackerMapwidget*) g_object_new (object_type, NULL);
#line 1 "../src/gtk/mapwidget.vala"
	return self;
#line 109 "mapwidget.c"
}

KctrackerMapwidget*
kctracker_mapwidget_new (void)
{
#line 1 "../src/gtk/mapwidget.vala"
	return kctracker_mapwidget_construct (KCTRACKER_TYPE_MAPWIDGET);
#line 117 "mapwidget.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 23 "../src/gtk/mapwidget.vala"
	return self ? g_object_ref (self) : NULL;
#line 125 "mapwidget.c"
}

static GObject *
kctracker_mapwidget_constructor (GType type,
                                 guint n_construct_properties,
                                 GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	KctrackerMapwidget * self;
	ShumateRasterRenderer* _tmp0_;
	ShumateRasterRenderer* _tmp1_;
	ShumateMapSource* _tmp2_;
	ShumateSimpleMap* _tmp3_ = NULL;
	ShumateViewport* viewport = NULL;
	ShumateSimpleMap* _tmp4_;
	ShumateViewport* _tmp5_;
	ShumateViewport* _tmp6_;
	ShumateViewport* _tmp7_;
	ShumateViewport* _tmp8_;
	ShumateViewport* _tmp9_;
	ShumateMarkerLayer* _tmp10_;
	KctrackerMarkermaker* marker = NULL;
	KctrackerMarkermaker* _tmp11_;
	GArray* markerArray = NULL;
	KctrackerMarkermaker* _tmp12_;
	GArray* _tmp13_;
	ShumateSimpleMap* _tmp20_;
	ShumateMarkerLayer* _tmp21_;
	ShumateSimpleMap* _tmp22_;
	GError* _inner_error0_ = NULL;
#line 6 "../src/gtk/mapwidget.vala"
	parent_class = G_OBJECT_CLASS (kctracker_mapwidget_parent_class);
#line 6 "../src/gtk/mapwidget.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 6 "../src/gtk/mapwidget.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, KCTRACKER_TYPE_MAPWIDGET, KctrackerMapwidget);
#line 7 "../src/gtk/mapwidget.vala"
	gtk_orientable_set_orientation ((GtkOrientable*) self, GTK_ORIENTATION_HORIZONTAL);
#line 10 "../src/gtk/mapwidget.vala"
	_tmp0_ = shumate_raster_renderer_new_full_from_url ("carto", "Carto Voyager", "MapSources: ©CARTO, © OpenStreetMap Contributers. Transit scheduling, " \
"geographic, and real-time data provided by permission of King County", "MULTIPLE SOURCES", (guint) 0, (guint) 20, (guint) 256, SHUMATE_MAP_PROJECTION_MERCATOR, "https://basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}.png");
#line 10 "../src/gtk/mapwidget.vala"
	_g_object_unref0 (self->rasterRenderer);
#line 10 "../src/gtk/mapwidget.vala"
	self->rasterRenderer = _tmp0_;
#line 23 "../src/gtk/mapwidget.vala"
	_tmp1_ = self->rasterRenderer;
#line 23 "../src/gtk/mapwidget.vala"
	_tmp2_ = _g_object_ref0 ((ShumateMapSource*) _tmp1_);
#line 23 "../src/gtk/mapwidget.vala"
	_tmp3_ = shumate_simple_map_new ();
#line 23 "../src/gtk/mapwidget.vala"
	gtk_widget_set_vexpand ((GtkWidget*) _tmp3_, TRUE);
#line 23 "../src/gtk/mapwidget.vala"
	gtk_widget_set_hexpand ((GtkWidget*) _tmp3_, TRUE);
#line 23 "../src/gtk/mapwidget.vala"
	shumate_simple_map_set_map_source (_tmp3_, _tmp2_);
#line 23 "../src/gtk/mapwidget.vala"
	_g_object_unref0 (_tmp2_);
#line 23 "../src/gtk/mapwidget.vala"
	shumate_simple_map_set_show_zoom_buttons (_tmp3_, FALSE);
#line 23 "../src/gtk/mapwidget.vala"
	g_object_ref_sink (_tmp3_);
#line 23 "../src/gtk/mapwidget.vala"
	_g_object_unref0 (self->shumateMap);
#line 23 "../src/gtk/mapwidget.vala"
	self->shumateMap = _tmp3_;
#line 30 "../src/gtk/mapwidget.vala"
	_tmp4_ = self->shumateMap;
#line 30 "../src/gtk/mapwidget.vala"
	_tmp5_ = shumate_simple_map_get_viewport (_tmp4_);
#line 30 "../src/gtk/mapwidget.vala"
	_tmp6_ = _g_object_ref0 (_tmp5_);
#line 30 "../src/gtk/mapwidget.vala"
	viewport = _tmp6_;
#line 31 "../src/gtk/mapwidget.vala"
	_tmp7_ = viewport;
#line 31 "../src/gtk/mapwidget.vala"
	shumate_location_set_location ((ShumateLocation*) _tmp7_, 47.606102, -122.254164);
#line 32 "../src/gtk/mapwidget.vala"
	_tmp8_ = viewport;
#line 32 "../src/gtk/mapwidget.vala"
	shumate_viewport_set_zoom_level (_tmp8_, (gdouble) 10);
#line 34 "../src/gtk/mapwidget.vala"
	_tmp9_ = viewport;
#line 34 "../src/gtk/mapwidget.vala"
	_tmp10_ = shumate_marker_layer_new (_tmp9_);
#line 34 "../src/gtk/mapwidget.vala"
	g_object_ref_sink (_tmp10_);
#line 34 "../src/gtk/mapwidget.vala"
	_g_object_unref0 (self->viewportLayer);
#line 34 "../src/gtk/mapwidget.vala"
	self->viewportLayer = _tmp10_;
#line 36 "../src/gtk/mapwidget.vala"
	_tmp11_ = kctracker_markermaker_new ();
#line 36 "../src/gtk/mapwidget.vala"
	marker = _tmp11_;
#line 37 "../src/gtk/mapwidget.vala"
	_tmp12_ = marker;
#line 37 "../src/gtk/mapwidget.vala"
	_tmp13_ = kctracker_markermaker_marker_compiler (_tmp12_, &_inner_error0_);
#line 37 "../src/gtk/mapwidget.vala"
	markerArray = _tmp13_;
#line 37 "../src/gtk/mapwidget.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 37 "../src/gtk/mapwidget.vala"
		_kctracker_markermaker_unref0 (marker);
#line 37 "../src/gtk/mapwidget.vala"
		_g_object_unref0 (viewport);
#line 37 "../src/gtk/mapwidget.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 37 "../src/gtk/mapwidget.vala"
		g_clear_error (&_inner_error0_);
#line 239 "mapwidget.c"
	}
	{
		gint i = 0;
#line 39 "../src/gtk/mapwidget.vala"
		i = 0;
#line 245 "mapwidget.c"
		{
			gboolean _tmp14_ = FALSE;
#line 39 "../src/gtk/mapwidget.vala"
			_tmp14_ = TRUE;
#line 39 "../src/gtk/mapwidget.vala"
			while (TRUE) {
#line 252 "mapwidget.c"
				GArray* _tmp16_;
				ShumateMarkerLayer* _tmp17_;
				GArray* _tmp18_;
				ShumateMarker* _tmp19_;
#line 39 "../src/gtk/mapwidget.vala"
				if (!_tmp14_) {
#line 259 "mapwidget.c"
					gint _tmp15_;
#line 39 "../src/gtk/mapwidget.vala"
					_tmp15_ = i;
#line 39 "../src/gtk/mapwidget.vala"
					i = _tmp15_ + 1;
#line 265 "mapwidget.c"
				}
#line 39 "../src/gtk/mapwidget.vala"
				_tmp14_ = FALSE;
#line 39 "../src/gtk/mapwidget.vala"
				_tmp16_ = markerArray;
#line 39 "../src/gtk/mapwidget.vala"
				if (!(((guint) i) < _tmp16_->len)) {
#line 39 "../src/gtk/mapwidget.vala"
					break;
#line 275 "mapwidget.c"
				}
#line 40 "../src/gtk/mapwidget.vala"
				_tmp17_ = self->viewportLayer;
#line 40 "../src/gtk/mapwidget.vala"
				_tmp18_ = markerArray;
#line 40 "../src/gtk/mapwidget.vala"
				_tmp19_ = g_array_index (_tmp18_, ShumateMarker*, (guint) i);
#line 40 "../src/gtk/mapwidget.vala"
				shumate_marker_layer_add_marker (_tmp17_, _tmp19_);
#line 285 "mapwidget.c"
			}
		}
	}
#line 43 "../src/gtk/mapwidget.vala"
	_tmp20_ = self->shumateMap;
#line 43 "../src/gtk/mapwidget.vala"
	_tmp21_ = self->viewportLayer;
#line 43 "../src/gtk/mapwidget.vala"
	shumate_simple_map_add_overlay_layer (_tmp20_, (ShumateLayer*) _tmp21_);
#line 44 "../src/gtk/mapwidget.vala"
	_tmp22_ = self->shumateMap;
#line 44 "../src/gtk/mapwidget.vala"
	gtk_box_append ((GtkBox*) self, (GtkWidget*) _tmp22_);
#line 6 "../src/gtk/mapwidget.vala"
	_g_array_unref0 (markerArray);
#line 6 "../src/gtk/mapwidget.vala"
	_kctracker_markermaker_unref0 (marker);
#line 6 "../src/gtk/mapwidget.vala"
	_g_object_unref0 (viewport);
#line 6 "../src/gtk/mapwidget.vala"
	return obj;
#line 307 "mapwidget.c"
}

static void
kctracker_mapwidget_class_init (KctrackerMapwidgetClass * klass,
                                gpointer klass_data)
{
#line 1 "../src/gtk/mapwidget.vala"
	kctracker_mapwidget_parent_class = g_type_class_peek_parent (klass);
#line 1 "../src/gtk/mapwidget.vala"
	G_OBJECT_CLASS (klass)->constructor = kctracker_mapwidget_constructor;
#line 1 "../src/gtk/mapwidget.vala"
	G_OBJECT_CLASS (klass)->finalize = kctracker_mapwidget_finalize;
#line 320 "mapwidget.c"
}

static void
kctracker_mapwidget_instance_init (KctrackerMapwidget * self,
                                   gpointer klass)
{
}

static void
kctracker_mapwidget_finalize (GObject * obj)
{
	KctrackerMapwidget * self;
#line 1 "../src/gtk/mapwidget.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, KCTRACKER_TYPE_MAPWIDGET, KctrackerMapwidget);
#line 2 "../src/gtk/mapwidget.vala"
	_g_object_unref0 (self->shumateMap);
#line 3 "../src/gtk/mapwidget.vala"
	_g_object_unref0 (self->viewportLayer);
#line 4 "../src/gtk/mapwidget.vala"
	_g_object_unref0 (self->rasterRenderer);
#line 1 "../src/gtk/mapwidget.vala"
	G_OBJECT_CLASS (kctracker_mapwidget_parent_class)->finalize (obj);
#line 343 "mapwidget.c"
}

static GType
kctracker_mapwidget_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (KctrackerMapwidgetClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) kctracker_mapwidget_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (KctrackerMapwidget), 0, (GInstanceInitFunc) kctracker_mapwidget_instance_init, NULL };
	GType kctracker_mapwidget_type_id;
	kctracker_mapwidget_type_id = g_type_register_static (gtk_box_get_type (), "KctrackerMapwidget", &g_define_type_info, 0);
	return kctracker_mapwidget_type_id;
}

GType
kctracker_mapwidget_get_type (void)
{
	static volatile gsize kctracker_mapwidget_type_id__once = 0;
	if (g_once_init_enter (&kctracker_mapwidget_type_id__once)) {
		GType kctracker_mapwidget_type_id;
		kctracker_mapwidget_type_id = kctracker_mapwidget_get_type_once ();
		g_once_init_leave (&kctracker_mapwidget_type_id__once, kctracker_mapwidget_type_id);
	}
	return kctracker_mapwidget_type_id__once;
}

