/* markermaker.c generated by valac 0.56.18, the Vala compiler
 * generated from markermaker.vala, do not modify */

#include <glib-object.h>
#include <glib.h>
#include <shumate/shumate.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <libsoup/soup.h>
#include <gio/gio.h>
#include <json-glib/json-glib.h>
#include <float.h>
#include <math.h>
#include <gtk/gtk.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define KCTRACKER_TYPE_MARKERMAKER (kctracker_markermaker_get_type ())
#define KCTRACKER_MARKERMAKER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KCTRACKER_TYPE_MARKERMAKER, KctrackerMarkermaker))
#define KCTRACKER_MARKERMAKER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KCTRACKER_TYPE_MARKERMAKER, KctrackerMarkermakerClass))
#define KCTRACKER_IS_MARKERMAKER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KCTRACKER_TYPE_MARKERMAKER))
#define KCTRACKER_IS_MARKERMAKER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KCTRACKER_TYPE_MARKERMAKER))
#define KCTRACKER_MARKERMAKER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KCTRACKER_TYPE_MARKERMAKER, KctrackerMarkermakerClass))

typedef struct _KctrackerMarkermaker KctrackerMarkermaker;
typedef struct _KctrackerMarkermakerClass KctrackerMarkermakerClass;
typedef struct _KctrackerMarkermakerPrivate KctrackerMarkermakerPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _json_array_unref0(var) ((var == NULL) ? NULL : (var = (json_array_unref (var), NULL)))
#define _json_object_unref0(var) ((var == NULL) ? NULL : (var = (json_object_unref (var), NULL)))
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))
#define _g_bytes_unref0(var) ((var == NULL) ? NULL : (var = (g_bytes_unref (var), NULL)))
typedef struct _Block1Data Block1Data;
#define _kctracker_markermaker_unref0(var) ((var == NULL) ? NULL : (var = (kctracker_markermaker_unref (var), NULL)))
typedef struct _KctrackerParamSpecMarkermaker KctrackerParamSpecMarkermaker;

struct _KctrackerMarkermaker {
	GTypeInstance parent_instance;
	volatile int ref_count;
	KctrackerMarkermakerPrivate * priv;
};

struct _KctrackerMarkermakerClass {
	GTypeClass parent_class;
	void (*finalize) (KctrackerMarkermaker *self);
};

struct _Block1Data {
	int _ref_count_;
	KctrackerMarkermaker* self;
	ShumateMarker* marker;
	gchar* routeInfo;
	gchar* routeDescription;
	gchar* routeType;
};

struct _KctrackerParamSpecMarkermaker {
	GParamSpec parent_instance;
};

static gpointer kctracker_markermaker_parent_class = NULL;

VALA_EXTERN gpointer kctracker_markermaker_ref (gpointer instance);
VALA_EXTERN void kctracker_markermaker_unref (gpointer instance);
VALA_EXTERN GParamSpec* kctracker_param_spec_markermaker (const gchar* name,
                                              const gchar* nick,
                                              const gchar* blurb,
                                              GType object_type,
                                              GParamFlags flags);
VALA_EXTERN void kctracker_value_set_markermaker (GValue* value,
                                      gpointer v_object);
VALA_EXTERN void kctracker_value_take_markermaker (GValue* value,
                                       gpointer v_object);
VALA_EXTERN gpointer kctracker_value_get_markermaker (const GValue* value);
VALA_EXTERN GType kctracker_markermaker_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KctrackerMarkermaker, kctracker_markermaker_unref)
VALA_EXTERN GArray* kctracker_markermaker_marker_compiler (KctrackerMarkermaker* self,
                                               GError** error);
static JsonNode* _vala_JsonNode_copy (JsonNode* self);
static void _vala_JsonNode_free (JsonNode* self);
static void _g_object_unref0_ (gpointer var);
static void _vala_ShumateMarker_free_function_content_of (gpointer data);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void _____lambda4_ (Block1Data* _data1_,
                    gint n,
                    gdouble x,
                    gdouble y);
static void ______lambda4__gtk_gesture_click_pressed (GtkGestureClick* _sender,
                                               gint n_press,
                                               gdouble x,
                                               gdouble y,
                                               gpointer self);
VALA_EXTERN KctrackerMarkermaker* kctracker_markermaker_new (void);
VALA_EXTERN KctrackerMarkermaker* kctracker_markermaker_construct (GType object_type);
static void kctracker_markermaker_finalize (KctrackerMarkermaker * obj);
static GType kctracker_markermaker_get_type_once (void);

static JsonNode*
_vala_JsonNode_copy (JsonNode* self)
{
#line 20 "../src/gtk/markermaker.vala"
	return g_boxed_copy (json_node_get_type (), self);
#line 124 "markermaker.c"
}

static gpointer
__vala_JsonNode_copy0 (gpointer self)
{
#line 20 "../src/gtk/markermaker.vala"
	return self ? _vala_JsonNode_copy (self) : NULL;
#line 132 "markermaker.c"
}

static gpointer
_json_object_ref0 (gpointer self)
{
#line 22 "../src/gtk/markermaker.vala"
	return self ? json_object_ref (self) : NULL;
#line 140 "markermaker.c"
}

static gpointer
_json_array_ref0 (gpointer self)
{
#line 24 "../src/gtk/markermaker.vala"
	return self ? json_array_ref (self) : NULL;
#line 148 "markermaker.c"
}

static void
_vala_JsonNode_free (JsonNode* self)
{
#line 29 "../src/gtk/markermaker.vala"
	g_boxed_free (json_node_get_type (), self);
#line 156 "markermaker.c"
}

static void
_g_object_unref0_ (gpointer var)
{
#line 39 "../src/gtk/markermaker.vala"
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
#line 164 "markermaker.c"
}

static void
_vala_ShumateMarker_free_function_content_of (gpointer data)
{
	ShumateMarker* self;
#line 39 "../src/gtk/markermaker.vala"
	self = *((ShumateMarker**) data);
#line 39 "../src/gtk/markermaker.vala"
	_g_object_unref0_ (self);
#line 175 "markermaker.c"
}

static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
#line 41 "../src/gtk/markermaker.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 41 "../src/gtk/markermaker.vala"
	return _data1_;
#line 185 "markermaker.c"
}

static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 41 "../src/gtk/markermaker.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 195 "markermaker.c"
		KctrackerMarkermaker* self;
#line 41 "../src/gtk/markermaker.vala"
		self = _data1_->self;
#line 41 "../src/gtk/markermaker.vala"
		_g_free0 (_data1_->routeType);
#line 41 "../src/gtk/markermaker.vala"
		_g_free0 (_data1_->routeDescription);
#line 41 "../src/gtk/markermaker.vala"
		_g_free0 (_data1_->routeInfo);
#line 41 "../src/gtk/markermaker.vala"
		_g_object_unref0 (_data1_->marker);
#line 41 "../src/gtk/markermaker.vala"
		_kctracker_markermaker_unref0 (self);
#line 41 "../src/gtk/markermaker.vala"
		g_slice_free (Block1Data, _data1_);
#line 211 "markermaker.c"
	}
}

static gboolean
string_contains (const gchar* self,
                 const gchar* needle)
{
	gchar* _tmp0_;
	gboolean result;
#line 1584 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, FALSE);
#line 1584 "glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, FALSE);
#line 1585 "glib-2.0.vapi"
	_tmp0_ = strstr ((gchar*) self, (gchar*) needle);
#line 1585 "glib-2.0.vapi"
	result = _tmp0_ != NULL;
#line 1585 "glib-2.0.vapi"
	return result;
#line 231 "markermaker.c"
}

static gchar
string_get (const gchar* self,
            glong index)
{
	gchar _tmp0_;
	gchar result;
#line 1283 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, '\0');
#line 1284 "glib-2.0.vapi"
	_tmp0_ = ((gchar*) self)[index];
#line 1284 "glib-2.0.vapi"
	result = _tmp0_;
#line 1284 "glib-2.0.vapi"
	return result;
#line 248 "markermaker.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 121 "../src/gtk/markermaker.vala"
	return self ? g_object_ref (self) : NULL;
#line 256 "markermaker.c"
}

static void
_____lambda4_ (Block1Data* _data1_,
               gint n,
               gdouble x,
               gdouble y)
{
	KctrackerMarkermaker* self;
	GtkPopover* popover = NULL;
	GtkPopover* _tmp0_;
	GtkBox* box = NULL;
	GtkBox* _tmp1_;
	GtkLabel* route_label = NULL;
	const gchar* _tmp2_;
	GtkLabel* _tmp3_;
	GtkLabel* _tmp4_;
	GtkLabel* _tmp5_;
	GtkLabel* route_type_label = NULL;
	const gchar* _tmp6_;
	GtkLabel* _tmp7_;
	GtkLabel* _tmp8_;
	const gchar* _tmp9_;
	GtkLabel* routeDescriptionCaption = NULL;
	const gchar* _tmp14_;
	GtkLabel* _tmp15_;
	GtkBox* _tmp16_;
	GtkLabel* _tmp17_;
	GtkBox* _tmp18_;
	GtkLabel* _tmp19_;
	GtkBox* _tmp20_;
	GtkPopover* _tmp21_;
	GtkBox* _tmp22_;
	GtkPopover* _tmp23_;
	ShumateMarker* _tmp24_;
	GtkPopover* _tmp25_;
#line 124 "../src/gtk/markermaker.vala"
	self = _data1_->self;
#line 125 "../src/gtk/markermaker.vala"
	_tmp0_ = (GtkPopover*) gtk_popover_new ();
#line 125 "../src/gtk/markermaker.vala"
	g_object_ref_sink (_tmp0_);
#line 125 "../src/gtk/markermaker.vala"
	popover = _tmp0_;
#line 126 "../src/gtk/markermaker.vala"
	_tmp1_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
#line 126 "../src/gtk/markermaker.vala"
	g_object_ref_sink (_tmp1_);
#line 126 "../src/gtk/markermaker.vala"
	box = _tmp1_;
#line 129 "../src/gtk/markermaker.vala"
	_tmp2_ = _data1_->routeInfo;
#line 129 "../src/gtk/markermaker.vala"
	_tmp3_ = (GtkLabel*) gtk_label_new (_tmp2_);
#line 129 "../src/gtk/markermaker.vala"
	g_object_ref_sink (_tmp3_);
#line 129 "../src/gtk/markermaker.vala"
	route_label = _tmp3_;
#line 130 "../src/gtk/markermaker.vala"
	_tmp4_ = route_label;
#line 130 "../src/gtk/markermaker.vala"
	gtk_widget_add_css_class ((GtkWidget*) _tmp4_, "title-1");
#line 131 "../src/gtk/markermaker.vala"
	_tmp5_ = route_label;
#line 131 "../src/gtk/markermaker.vala"
	gtk_widget_add_css_class ((GtkWidget*) _tmp5_, "bold");
#line 133 "../src/gtk/markermaker.vala"
	_tmp6_ = _data1_->routeType;
#line 133 "../src/gtk/markermaker.vala"
	_tmp7_ = (GtkLabel*) gtk_label_new (_tmp6_);
#line 133 "../src/gtk/markermaker.vala"
	g_object_ref_sink (_tmp7_);
#line 133 "../src/gtk/markermaker.vala"
	route_type_label = _tmp7_;
#line 134 "../src/gtk/markermaker.vala"
	_tmp8_ = route_type_label;
#line 134 "../src/gtk/markermaker.vala"
	gtk_widget_add_css_class ((GtkWidget*) _tmp8_, "title-3");
#line 137 "../src/gtk/markermaker.vala"
	_tmp9_ = _data1_->routeType;
#line 137 "../src/gtk/markermaker.vala"
	if (g_strcmp0 (_tmp9_, "Express Route") == 0) {
#line 339 "markermaker.c"
		GtkLabel* _tmp10_;
#line 139 "../src/gtk/markermaker.vala"
		_tmp10_ = route_type_label;
#line 139 "../src/gtk/markermaker.vala"
		gtk_widget_add_css_class ((GtkWidget*) _tmp10_, "Express");
#line 345 "markermaker.c"
	} else {
		const gchar* _tmp11_;
#line 141 "../src/gtk/markermaker.vala"
		_tmp11_ = _data1_->routeType;
#line 141 "../src/gtk/markermaker.vala"
		if (g_strcmp0 (_tmp11_, "Rapid Ride") == 0) {
#line 352 "markermaker.c"
			GtkLabel* _tmp12_;
#line 143 "../src/gtk/markermaker.vala"
			_tmp12_ = route_type_label;
#line 143 "../src/gtk/markermaker.vala"
			gtk_widget_add_css_class ((GtkWidget*) _tmp12_, "Rapid");
#line 358 "markermaker.c"
		} else {
			GtkLabel* _tmp13_;
#line 148 "../src/gtk/markermaker.vala"
			_tmp13_ = route_type_label;
#line 148 "../src/gtk/markermaker.vala"
			gtk_widget_add_css_class ((GtkWidget*) _tmp13_, "Metro");
#line 365 "markermaker.c"
		}
	}
#line 151 "../src/gtk/markermaker.vala"
	_tmp14_ = _data1_->routeDescription;
#line 151 "../src/gtk/markermaker.vala"
	_tmp15_ = (GtkLabel*) gtk_label_new (_tmp14_);
#line 151 "../src/gtk/markermaker.vala"
	g_object_ref_sink (_tmp15_);
#line 151 "../src/gtk/markermaker.vala"
	routeDescriptionCaption = _tmp15_;
#line 152 "../src/gtk/markermaker.vala"
	gtk_widget_add_css_class ((GtkWidget*) routeDescriptionCaption, "title-5");
#line 156 "../src/gtk/markermaker.vala"
	_tmp16_ = box;
#line 156 "../src/gtk/markermaker.vala"
	_tmp17_ = route_label;
#line 156 "../src/gtk/markermaker.vala"
	gtk_box_append (_tmp16_, (GtkWidget*) _tmp17_);
#line 157 "../src/gtk/markermaker.vala"
	_tmp18_ = box;
#line 157 "../src/gtk/markermaker.vala"
	_tmp19_ = route_type_label;
#line 157 "../src/gtk/markermaker.vala"
	gtk_box_append (_tmp18_, (GtkWidget*) _tmp19_);
#line 158 "../src/gtk/markermaker.vala"
	_tmp20_ = box;
#line 158 "../src/gtk/markermaker.vala"
	gtk_box_append (_tmp20_, (GtkWidget*) routeDescriptionCaption);
#line 160 "../src/gtk/markermaker.vala"
	_tmp21_ = popover;
#line 160 "../src/gtk/markermaker.vala"
	_tmp22_ = box;
#line 160 "../src/gtk/markermaker.vala"
	gtk_popover_set_child (_tmp21_, (GtkWidget*) _tmp22_);
#line 161 "../src/gtk/markermaker.vala"
	_tmp23_ = popover;
#line 161 "../src/gtk/markermaker.vala"
	_tmp24_ = _data1_->marker;
#line 161 "../src/gtk/markermaker.vala"
	gtk_widget_set_parent ((GtkWidget*) _tmp23_, (GtkWidget*) _tmp24_);
#line 162 "../src/gtk/markermaker.vala"
	_tmp25_ = popover;
#line 162 "../src/gtk/markermaker.vala"
	gtk_popover_popup (_tmp25_);
#line 124 "../src/gtk/markermaker.vala"
	_g_object_unref0 (routeDescriptionCaption);
#line 124 "../src/gtk/markermaker.vala"
	_g_object_unref0 (route_type_label);
#line 124 "../src/gtk/markermaker.vala"
	_g_object_unref0 (route_label);
#line 124 "../src/gtk/markermaker.vala"
	_g_object_unref0 (box);
#line 124 "../src/gtk/markermaker.vala"
	_g_object_unref0 (popover);
#line 420 "markermaker.c"
}

static void
______lambda4__gtk_gesture_click_pressed (GtkGestureClick* _sender,
                                          gint n_press,
                                          gdouble x,
                                          gdouble y,
                                          gpointer self)
{
#line 124 "../src/gtk/markermaker.vala"
	_____lambda4_ (self, n_press, x, y);
#line 432 "markermaker.c"
}

GArray*
kctracker_markermaker_marker_compiler (KctrackerMarkermaker* self,
                                       GError** error)
{
	FILE* _tmp0_;
	gchar* kcjsonurl = NULL;
	gchar* _tmp1_;
	SoupSession* session = NULL;
	SoupSession* _tmp2_;
	SoupMessage* message = NULL;
	const gchar* _tmp3_;
	SoupMessage* _tmp4_;
	GInputStream* response = NULL;
	SoupSession* _tmp5_;
	SoupMessage* _tmp6_;
	GInputStream* _tmp7_;
	JsonParser* parser = NULL;
	JsonParser* _tmp8_;
	JsonParser* _tmp9_;
	GInputStream* _tmp10_;
	JsonNode* node = NULL;
	JsonParser* _tmp11_;
	JsonNode* _tmp12_;
	JsonNode* _tmp13_;
	JsonObject* object = NULL;
	JsonNode* _tmp14_;
	JsonObject* _tmp15_;
	JsonObject* _tmp16_;
	JsonArray* entityArray = NULL;
	JsonObject* _tmp17_;
	JsonArray* _tmp18_;
	JsonArray* _tmp19_;
	JsonParser* localParser = NULL;
	JsonParser* _tmp20_;
	gchar* resource_path = NULL;
	gchar* _tmp21_;
	GBytes* resource = NULL;
	const gchar* _tmp22_;
	GBytes* _tmp23_;
	JsonParser* _tmp24_;
	GBytes* _tmp25_;
	gsize _tmp26_ = 0;
	guint8* _tmp27_;
	JsonBuilder* jsonBuilder = NULL;
	JsonBuilder* _tmp28_;
	JsonBuilder* _tmp29_;
	JsonNode* localNode = NULL;
	JsonParser* _tmp30_;
	JsonNode* _tmp31_;
	JsonNode* _tmp32_;
	GArray* markerList = NULL;
	GArray* _tmp33_;
	GError* _inner_error0_ = NULL;
	GArray* result;
#line 9 "../src/gtk/markermaker.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 10 "../src/gtk/markermaker.vala"
	_tmp0_ = stdout;
#line 10 "../src/gtk/markermaker.vala"
	fprintf (_tmp0_, "test");
#line 11 "../src/gtk/markermaker.vala"
	_tmp1_ = g_strdup ("https://s3.amazonaws.com/kcm-alerts-realtime-prod/vehiclepositions_enh" \
"anced.json");
#line 11 "../src/gtk/markermaker.vala"
	kcjsonurl = _tmp1_;
#line 12 "../src/gtk/markermaker.vala"
	_tmp2_ = soup_session_new ();
#line 12 "../src/gtk/markermaker.vala"
	session = _tmp2_;
#line 13 "../src/gtk/markermaker.vala"
	_tmp3_ = kcjsonurl;
#line 13 "../src/gtk/markermaker.vala"
	_tmp4_ = soup_message_new ("GET", _tmp3_);
#line 13 "../src/gtk/markermaker.vala"
	message = _tmp4_;
#line 14 "../src/gtk/markermaker.vala"
	_tmp5_ = session;
#line 14 "../src/gtk/markermaker.vala"
	_tmp6_ = message;
#line 14 "../src/gtk/markermaker.vala"
	_tmp7_ = soup_session_send (_tmp5_, _tmp6_, NULL, &_inner_error0_);
#line 14 "../src/gtk/markermaker.vala"
	response = _tmp7_;
#line 14 "../src/gtk/markermaker.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 14 "../src/gtk/markermaker.vala"
		g_propagate_error (error, _inner_error0_);
#line 14 "../src/gtk/markermaker.vala"
		_g_object_unref0 (message);
#line 14 "../src/gtk/markermaker.vala"
		_g_object_unref0 (session);
#line 14 "../src/gtk/markermaker.vala"
		_g_free0 (kcjsonurl);
#line 14 "../src/gtk/markermaker.vala"
		return NULL;
#line 529 "markermaker.c"
	}
#line 16 "../src/gtk/markermaker.vala"
	_tmp8_ = json_parser_new ();
#line 16 "../src/gtk/markermaker.vala"
	parser = _tmp8_;
#line 18 "../src/gtk/markermaker.vala"
	_tmp9_ = parser;
#line 18 "../src/gtk/markermaker.vala"
	_tmp10_ = response;
#line 18 "../src/gtk/markermaker.vala"
	json_parser_load_from_stream (_tmp9_, _tmp10_, NULL, &_inner_error0_);
#line 18 "../src/gtk/markermaker.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 18 "../src/gtk/markermaker.vala"
		g_propagate_error (error, _inner_error0_);
#line 18 "../src/gtk/markermaker.vala"
		_g_object_unref0 (parser);
#line 18 "../src/gtk/markermaker.vala"
		_g_object_unref0 (response);
#line 18 "../src/gtk/markermaker.vala"
		_g_object_unref0 (message);
#line 18 "../src/gtk/markermaker.vala"
		_g_object_unref0 (session);
#line 18 "../src/gtk/markermaker.vala"
		_g_free0 (kcjsonurl);
#line 18 "../src/gtk/markermaker.vala"
		return NULL;
#line 557 "markermaker.c"
	}
#line 20 "../src/gtk/markermaker.vala"
	_tmp11_ = parser;
#line 20 "../src/gtk/markermaker.vala"
	_tmp12_ = json_parser_get_root (_tmp11_);
#line 20 "../src/gtk/markermaker.vala"
	_tmp13_ = __vala_JsonNode_copy0 (_tmp12_);
#line 20 "../src/gtk/markermaker.vala"
	node = _tmp13_;
#line 22 "../src/gtk/markermaker.vala"
	_tmp14_ = node;
#line 22 "../src/gtk/markermaker.vala"
	_tmp15_ = json_node_get_object (_tmp14_);
#line 22 "../src/gtk/markermaker.vala"
	_tmp16_ = _json_object_ref0 (_tmp15_);
#line 22 "../src/gtk/markermaker.vala"
	object = _tmp16_;
#line 24 "../src/gtk/markermaker.vala"
	_tmp17_ = object;
#line 24 "../src/gtk/markermaker.vala"
	_tmp18_ = json_object_get_array_member (_tmp17_, "entity");
#line 24 "../src/gtk/markermaker.vala"
	_tmp19_ = _json_array_ref0 (_tmp18_);
#line 24 "../src/gtk/markermaker.vala"
	entityArray = _tmp19_;
#line 26 "../src/gtk/markermaker.vala"
	_tmp20_ = json_parser_new ();
#line 26 "../src/gtk/markermaker.vala"
	localParser = _tmp20_;
#line 28 "../src/gtk/markermaker.vala"
	_tmp21_ = g_strdup ("/me/flagmaster/kctracker/gtk/routes.json");
#line 28 "../src/gtk/markermaker.vala"
	resource_path = _tmp21_;
#line 29 "../src/gtk/markermaker.vala"
	_tmp22_ = resource_path;
#line 29 "../src/gtk/markermaker.vala"
	_tmp23_ = g_resources_lookup_data (_tmp22_, G_RESOURCE_LOOKUP_FLAGS_NONE, &_inner_error0_);
#line 29 "../src/gtk/markermaker.vala"
	resource = _tmp23_;
#line 29 "../src/gtk/markermaker.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 29 "../src/gtk/markermaker.vala"
		g_propagate_error (error, _inner_error0_);
#line 29 "../src/gtk/markermaker.vala"
		_g_free0 (resource_path);
#line 29 "../src/gtk/markermaker.vala"
		_g_object_unref0 (localParser);
#line 29 "../src/gtk/markermaker.vala"
		_json_array_unref0 (entityArray);
#line 29 "../src/gtk/markermaker.vala"
		_json_object_unref0 (object);
#line 29 "../src/gtk/markermaker.vala"
		__vala_JsonNode_free0 (node);
#line 29 "../src/gtk/markermaker.vala"
		_g_object_unref0 (parser);
#line 29 "../src/gtk/markermaker.vala"
		_g_object_unref0 (response);
#line 29 "../src/gtk/markermaker.vala"
		_g_object_unref0 (message);
#line 29 "../src/gtk/markermaker.vala"
		_g_object_unref0 (session);
#line 29 "../src/gtk/markermaker.vala"
		_g_free0 (kcjsonurl);
#line 29 "../src/gtk/markermaker.vala"
		return NULL;
#line 623 "markermaker.c"
	}
#line 30 "../src/gtk/markermaker.vala"
	_tmp24_ = localParser;
#line 30 "../src/gtk/markermaker.vala"
	_tmp25_ = resource;
#line 30 "../src/gtk/markermaker.vala"
	_tmp27_ = g_bytes_get_data (_tmp25_, &_tmp26_);
#line 30 "../src/gtk/markermaker.vala"
	json_parser_load_from_data (_tmp24_, (const gchar*) _tmp27_, (gssize) -1, &_inner_error0_);
#line 30 "../src/gtk/markermaker.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 30 "../src/gtk/markermaker.vala"
		g_propagate_error (error, _inner_error0_);
#line 30 "../src/gtk/markermaker.vala"
		_g_bytes_unref0 (resource);
#line 30 "../src/gtk/markermaker.vala"
		_g_free0 (resource_path);
#line 30 "../src/gtk/markermaker.vala"
		_g_object_unref0 (localParser);
#line 30 "../src/gtk/markermaker.vala"
		_json_array_unref0 (entityArray);
#line 30 "../src/gtk/markermaker.vala"
		_json_object_unref0 (object);
#line 30 "../src/gtk/markermaker.vala"
		__vala_JsonNode_free0 (node);
#line 30 "../src/gtk/markermaker.vala"
		_g_object_unref0 (parser);
#line 30 "../src/gtk/markermaker.vala"
		_g_object_unref0 (response);
#line 30 "../src/gtk/markermaker.vala"
		_g_object_unref0 (message);
#line 30 "../src/gtk/markermaker.vala"
		_g_object_unref0 (session);
#line 30 "../src/gtk/markermaker.vala"
		_g_free0 (kcjsonurl);
#line 30 "../src/gtk/markermaker.vala"
		return NULL;
#line 661 "markermaker.c"
	}
#line 32 "../src/gtk/markermaker.vala"
	_tmp28_ = json_builder_new ();
#line 32 "../src/gtk/markermaker.vala"
	jsonBuilder = _tmp28_;
#line 33 "../src/gtk/markermaker.vala"
	_tmp29_ = jsonBuilder;
#line 33 "../src/gtk/markermaker.vala"
	json_builder_begin_object (_tmp29_);
#line 37 "../src/gtk/markermaker.vala"
	_tmp30_ = localParser;
#line 37 "../src/gtk/markermaker.vala"
	_tmp31_ = json_parser_get_root (_tmp30_);
#line 37 "../src/gtk/markermaker.vala"
	_tmp32_ = __vala_JsonNode_copy0 (_tmp31_);
#line 37 "../src/gtk/markermaker.vala"
	localNode = _tmp32_;
#line 39 "../src/gtk/markermaker.vala"
	_tmp33_ = g_array_new (TRUE, TRUE, sizeof (ShumateMarker*));
#line 39 "../src/gtk/markermaker.vala"
	g_array_set_clear_func (_tmp33_, (GDestroyNotify) _vala_ShumateMarker_free_function_content_of);
#line 39 "../src/gtk/markermaker.vala"
	markerList = _tmp33_;
#line 685 "markermaker.c"
	{
		gint i = 0;
#line 41 "../src/gtk/markermaker.vala"
		i = 0;
#line 690 "markermaker.c"
		{
			gboolean _tmp34_ = FALSE;
#line 41 "../src/gtk/markermaker.vala"
			_tmp34_ = TRUE;
#line 41 "../src/gtk/markermaker.vala"
			while (TRUE) {
#line 697 "markermaker.c"
				Block1Data* _data1_;
				JsonArray* _tmp36_;
				JsonNode* entityPostition = NULL;
				JsonArray* _tmp37_;
				JsonNode* _tmp38_;
				JsonNode* _tmp39_;
				JsonObject* entityObject = NULL;
				JsonNode* _tmp40_;
				JsonObject* _tmp41_;
				JsonObject* _tmp42_;
				gchar* id = NULL;
				JsonObject* _tmp43_;
				const gchar* _tmp44_;
				gchar* _tmp45_;
				JsonNode* outerVehicleNode = NULL;
				JsonObject* _tmp46_;
				JsonNode* _tmp47_;
				JsonNode* _tmp48_;
				JsonObject* outerVehicleObject = NULL;
				JsonNode* _tmp49_;
				JsonObject* _tmp50_;
				JsonObject* _tmp51_;
				JsonNode* innerVehicleNode = NULL;
				JsonObject* _tmp52_;
				JsonNode* _tmp53_;
				JsonNode* _tmp54_;
				JsonObject* innerVehicleObject = NULL;
				JsonNode* _tmp55_;
				JsonObject* _tmp56_;
				JsonObject* _tmp57_;
				gdouble latitude = 0.0;
				JsonObject* _tmp58_;
				gdouble longitude = 0.0;
				JsonObject* _tmp59_;
				JsonNode* tripNode = NULL;
				JsonObject* _tmp60_;
				JsonNode* _tmp61_;
				JsonNode* _tmp62_;
				JsonObject* tripObject = NULL;
				JsonNode* _tmp63_;
				JsonObject* _tmp64_;
				JsonObject* _tmp65_;
				gchar* tripID = NULL;
				JsonObject* _tmp66_;
				const gchar* _tmp67_;
				gchar* _tmp68_;
				gchar* routeID = NULL;
				JsonObject* _tmp69_;
				const gchar* _tmp70_;
				gchar* _tmp71_;
				GtkImage* image = NULL;
				GtkImage* _tmp72_;
				GtkImage* _tmp73_;
				ShumateMarker* _tmp74_;
				ShumateMarker* _tmp75_;
				ShumateMarker* _tmp76_;
				GtkImage* _tmp77_;
				ShumateMarker* _tmp78_;
				JsonArray* root_array = NULL;
				JsonNode* _tmp79_;
				JsonArray* _tmp80_;
				JsonArray* _tmp81_;
				gchar* _tmp82_;
				gchar* _tmp83_;
				gchar* _tmp84_;
				GtkGestureClick* gesture = NULL;
				GtkGestureClick* _tmp118_;
				ShumateMarker* _tmp119_;
				GtkGestureClick* _tmp120_;
				GtkEventController* _tmp121_;
				GtkGestureClick* _tmp122_;
				JsonBuilder* _tmp123_;
				const gchar* _tmp124_;
				JsonBuilder* _tmp125_;
				JsonBuilder* _tmp126_;
				const gchar* _tmp127_;
				JsonBuilder* _tmp128_;
				JsonBuilder* _tmp129_;
				JsonBuilder* _tmp130_;
				JsonBuilder* _tmp131_;
				JsonBuilder* _tmp132_;
				JsonBuilder* _tmp133_;
				JsonBuilder* _tmp134_;
				GArray* _tmp135_;
				ShumateMarker* _tmp136_;
				ShumateMarker* _tmp137_;
#line 41 "../src/gtk/markermaker.vala"
				_data1_ = g_slice_new0 (Block1Data);
#line 41 "../src/gtk/markermaker.vala"
				_data1_->_ref_count_ = 1;
#line 41 "../src/gtk/markermaker.vala"
				_data1_->self = kctracker_markermaker_ref (self);
#line 41 "../src/gtk/markermaker.vala"
				if (!_tmp34_) {
#line 792 "markermaker.c"
					gint _tmp35_;
#line 41 "../src/gtk/markermaker.vala"
					_tmp35_ = i;
#line 41 "../src/gtk/markermaker.vala"
					i = _tmp35_ + 1;
#line 798 "markermaker.c"
				}
#line 41 "../src/gtk/markermaker.vala"
				_tmp34_ = FALSE;
#line 41 "../src/gtk/markermaker.vala"
				_tmp36_ = entityArray;
#line 41 "../src/gtk/markermaker.vala"
				if (!(((guint) i) < json_array_get_length (_tmp36_))) {
#line 41 "../src/gtk/markermaker.vala"
					block1_data_unref (_data1_);
#line 41 "../src/gtk/markermaker.vala"
					_data1_ = NULL;
#line 41 "../src/gtk/markermaker.vala"
					break;
#line 812 "markermaker.c"
				}
#line 44 "../src/gtk/markermaker.vala"
				_tmp37_ = entityArray;
#line 44 "../src/gtk/markermaker.vala"
				_tmp38_ = json_array_get_element (_tmp37_, (guint) i);
#line 44 "../src/gtk/markermaker.vala"
				_tmp39_ = __vala_JsonNode_copy0 (_tmp38_);
#line 44 "../src/gtk/markermaker.vala"
				entityPostition = _tmp39_;
#line 46 "../src/gtk/markermaker.vala"
				_tmp40_ = entityPostition;
#line 46 "../src/gtk/markermaker.vala"
				_tmp41_ = json_node_get_object (_tmp40_);
#line 46 "../src/gtk/markermaker.vala"
				_tmp42_ = _json_object_ref0 (_tmp41_);
#line 46 "../src/gtk/markermaker.vala"
				entityObject = _tmp42_;
#line 48 "../src/gtk/markermaker.vala"
				_tmp43_ = entityObject;
#line 48 "../src/gtk/markermaker.vala"
				_tmp44_ = json_object_get_string_member (_tmp43_, "id");
#line 48 "../src/gtk/markermaker.vala"
				_tmp45_ = g_strdup (_tmp44_);
#line 48 "../src/gtk/markermaker.vala"
				id = _tmp45_;
#line 51 "../src/gtk/markermaker.vala"
				_tmp46_ = entityObject;
#line 51 "../src/gtk/markermaker.vala"
				_tmp47_ = json_object_get_member (_tmp46_, "vehicle");
#line 51 "../src/gtk/markermaker.vala"
				_tmp48_ = __vala_JsonNode_copy0 (_tmp47_);
#line 51 "../src/gtk/markermaker.vala"
				outerVehicleNode = _tmp48_;
#line 53 "../src/gtk/markermaker.vala"
				_tmp49_ = outerVehicleNode;
#line 53 "../src/gtk/markermaker.vala"
				_tmp50_ = json_node_get_object (_tmp49_);
#line 53 "../src/gtk/markermaker.vala"
				_tmp51_ = _json_object_ref0 (_tmp50_);
#line 53 "../src/gtk/markermaker.vala"
				outerVehicleObject = _tmp51_;
#line 55 "../src/gtk/markermaker.vala"
				_tmp52_ = outerVehicleObject;
#line 55 "../src/gtk/markermaker.vala"
				_tmp53_ = json_object_get_member (_tmp52_, "position");
#line 55 "../src/gtk/markermaker.vala"
				_tmp54_ = __vala_JsonNode_copy0 (_tmp53_);
#line 55 "../src/gtk/markermaker.vala"
				innerVehicleNode = _tmp54_;
#line 56 "../src/gtk/markermaker.vala"
				_tmp55_ = innerVehicleNode;
#line 56 "../src/gtk/markermaker.vala"
				_tmp56_ = json_node_get_object (_tmp55_);
#line 56 "../src/gtk/markermaker.vala"
				_tmp57_ = _json_object_ref0 (_tmp56_);
#line 56 "../src/gtk/markermaker.vala"
				innerVehicleObject = _tmp57_;
#line 57 "../src/gtk/markermaker.vala"
				_tmp58_ = innerVehicleObject;
#line 57 "../src/gtk/markermaker.vala"
				latitude = json_object_get_double_member (_tmp58_, "latitude");
#line 58 "../src/gtk/markermaker.vala"
				_tmp59_ = innerVehicleObject;
#line 58 "../src/gtk/markermaker.vala"
				longitude = json_object_get_double_member (_tmp59_, "longitude");
#line 61 "../src/gtk/markermaker.vala"
				_tmp60_ = outerVehicleObject;
#line 61 "../src/gtk/markermaker.vala"
				_tmp61_ = json_object_get_member (_tmp60_, "trip");
#line 61 "../src/gtk/markermaker.vala"
				_tmp62_ = __vala_JsonNode_copy0 (_tmp61_);
#line 61 "../src/gtk/markermaker.vala"
				tripNode = _tmp62_;
#line 62 "../src/gtk/markermaker.vala"
				_tmp63_ = tripNode;
#line 62 "../src/gtk/markermaker.vala"
				_tmp64_ = json_node_get_object (_tmp63_);
#line 62 "../src/gtk/markermaker.vala"
				_tmp65_ = _json_object_ref0 (_tmp64_);
#line 62 "../src/gtk/markermaker.vala"
				tripObject = _tmp65_;
#line 63 "../src/gtk/markermaker.vala"
				_tmp66_ = tripObject;
#line 63 "../src/gtk/markermaker.vala"
				_tmp67_ = json_object_get_string_member (_tmp66_, "trip_id");
#line 63 "../src/gtk/markermaker.vala"
				_tmp68_ = g_strdup (_tmp67_);
#line 63 "../src/gtk/markermaker.vala"
				tripID = _tmp68_;
#line 64 "../src/gtk/markermaker.vala"
				_tmp69_ = tripObject;
#line 64 "../src/gtk/markermaker.vala"
				_tmp70_ = json_object_get_string_member (_tmp69_, "route_id");
#line 64 "../src/gtk/markermaker.vala"
				_tmp71_ = g_strdup (_tmp70_);
#line 64 "../src/gtk/markermaker.vala"
				routeID = _tmp71_;
#line 77 "../src/gtk/markermaker.vala"
				_tmp72_ = (GtkImage*) gtk_image_new ();
#line 77 "../src/gtk/markermaker.vala"
				g_object_ref_sink (_tmp72_);
#line 77 "../src/gtk/markermaker.vala"
				image = _tmp72_;
#line 78 "../src/gtk/markermaker.vala"
				_tmp73_ = image;
#line 78 "../src/gtk/markermaker.vala"
				gtk_image_set_from_icon_name (_tmp73_, "compass-symbolic");
#line 80 "../src/gtk/markermaker.vala"
				_tmp74_ = shumate_marker_new ();
#line 80 "../src/gtk/markermaker.vala"
				g_object_ref_sink (_tmp74_);
#line 80 "../src/gtk/markermaker.vala"
				_data1_->marker = _tmp74_;
#line 81 "../src/gtk/markermaker.vala"
				_tmp75_ = _data1_->marker;
#line 81 "../src/gtk/markermaker.vala"
				shumate_location_set_location ((ShumateLocation*) _tmp75_, latitude, longitude);
#line 82 "../src/gtk/markermaker.vala"
				_tmp76_ = _data1_->marker;
#line 82 "../src/gtk/markermaker.vala"
				_tmp77_ = image;
#line 82 "../src/gtk/markermaker.vala"
				shumate_marker_set_child (_tmp76_, (GtkWidget*) _tmp77_);
#line 83 "../src/gtk/markermaker.vala"
				_tmp78_ = _data1_->marker;
#line 83 "../src/gtk/markermaker.vala"
				shumate_marker_set_selectable (_tmp78_, TRUE);
#line 86 "../src/gtk/markermaker.vala"
				_tmp79_ = localNode;
#line 86 "../src/gtk/markermaker.vala"
				_tmp80_ = json_node_get_array (_tmp79_);
#line 86 "../src/gtk/markermaker.vala"
				_tmp81_ = _json_array_ref0 (_tmp80_);
#line 86 "../src/gtk/markermaker.vala"
				root_array = _tmp81_;
#line 87 "../src/gtk/markermaker.vala"
				_tmp82_ = g_strdup ("");
#line 87 "../src/gtk/markermaker.vala"
				_data1_->routeInfo = _tmp82_;
#line 88 "../src/gtk/markermaker.vala"
				_tmp83_ = g_strdup ("");
#line 88 "../src/gtk/markermaker.vala"
				_data1_->routeDescription = _tmp83_;
#line 89 "../src/gtk/markermaker.vala"
				_tmp84_ = g_strdup ("");
#line 89 "../src/gtk/markermaker.vala"
				_data1_->routeType = _tmp84_;
#line 960 "markermaker.c"
				{
					gint a = 0;
#line 93 "../src/gtk/markermaker.vala"
					a = 0;
#line 965 "markermaker.c"
					{
						gboolean _tmp85_ = FALSE;
#line 93 "../src/gtk/markermaker.vala"
						_tmp85_ = TRUE;
#line 93 "../src/gtk/markermaker.vala"
						while (TRUE) {
#line 972 "markermaker.c"
							JsonArray* _tmp87_;
							JsonObject* route_object = NULL;
							JsonArray* _tmp88_;
							JsonNode* _tmp89_;
							JsonObject* _tmp90_;
							JsonObject* _tmp91_;
							JsonObject* _tmp92_;
							gchar* _tmp93_;
							gchar* _tmp94_;
							const gchar* _tmp95_;
							gboolean _tmp96_;
#line 93 "../src/gtk/markermaker.vala"
							if (!_tmp85_) {
#line 986 "markermaker.c"
								gint _tmp86_;
#line 93 "../src/gtk/markermaker.vala"
								_tmp86_ = a;
#line 93 "../src/gtk/markermaker.vala"
								a = _tmp86_ + 1;
#line 992 "markermaker.c"
							}
#line 93 "../src/gtk/markermaker.vala"
							_tmp85_ = FALSE;
#line 93 "../src/gtk/markermaker.vala"
							_tmp87_ = root_array;
#line 93 "../src/gtk/markermaker.vala"
							if (!(((guint) a) < json_array_get_length (_tmp87_))) {
#line 93 "../src/gtk/markermaker.vala"
								break;
#line 1002 "markermaker.c"
							}
#line 94 "../src/gtk/markermaker.vala"
							_tmp88_ = root_array;
#line 94 "../src/gtk/markermaker.vala"
							_tmp89_ = json_array_get_element (_tmp88_, (guint) a);
#line 94 "../src/gtk/markermaker.vala"
							_tmp90_ = json_node_get_object (_tmp89_);
#line 94 "../src/gtk/markermaker.vala"
							_tmp91_ = _json_object_ref0 (_tmp90_);
#line 94 "../src/gtk/markermaker.vala"
							route_object = _tmp91_;
#line 95 "../src/gtk/markermaker.vala"
							_tmp92_ = route_object;
#line 95 "../src/gtk/markermaker.vala"
							_tmp93_ = g_strdup_printf ("%u", json_object_get_int_member (_tmp92_, "route_id"));
#line 95 "../src/gtk/markermaker.vala"
							_tmp94_ = _tmp93_;
#line 95 "../src/gtk/markermaker.vala"
							_tmp95_ = routeID;
#line 95 "../src/gtk/markermaker.vala"
							_tmp96_ = g_strcmp0 (_tmp94_, _tmp95_) == 0;
#line 95 "../src/gtk/markermaker.vala"
							_g_free0 (_tmp94_);
#line 95 "../src/gtk/markermaker.vala"
							if (_tmp96_) {
#line 1028 "markermaker.c"
								JsonObject* _tmp97_;
								const gchar* _tmp98_;
								gchar* _tmp99_;
								const gchar* _tmp100_;
								JsonObject* _tmp115_;
								const gchar* _tmp116_;
								gchar* _tmp117_;
#line 96 "../src/gtk/markermaker.vala"
								_tmp97_ = route_object;
#line 96 "../src/gtk/markermaker.vala"
								_tmp98_ = json_object_get_string_member (_tmp97_, "route_short_name");
#line 96 "../src/gtk/markermaker.vala"
								_tmp99_ = g_strdup (_tmp98_);
#line 96 "../src/gtk/markermaker.vala"
								_g_free0 (_data1_->routeInfo);
#line 96 "../src/gtk/markermaker.vala"
								_data1_->routeInfo = _tmp99_;
#line 98 "../src/gtk/markermaker.vala"
								_tmp100_ = _data1_->routeInfo;
#line 98 "../src/gtk/markermaker.vala"
								if (string_contains (_tmp100_, "Line")) {
#line 1050 "markermaker.c"
									GtkImage* _tmp101_;
									gchar* _tmp102_;
#line 99 "../src/gtk/markermaker.vala"
									_tmp101_ = image;
#line 99 "../src/gtk/markermaker.vala"
									gtk_widget_add_css_class ((GtkWidget*) _tmp101_, "Rapid");
#line 100 "../src/gtk/markermaker.vala"
									_tmp102_ = g_strdup ("Rapid Ride");
#line 100 "../src/gtk/markermaker.vala"
									_g_free0 (_data1_->routeType);
#line 100 "../src/gtk/markermaker.vala"
									_data1_->routeType = _tmp102_;
#line 1063 "markermaker.c"
								} else {
									gboolean _tmp103_ = FALSE;
									const gchar* _tmp104_;
									gchar* _tmp105_;
									gchar* _tmp106_;
									gboolean _tmp107_;
#line 102 "../src/gtk/markermaker.vala"
									_tmp104_ = _data1_->routeInfo;
#line 102 "../src/gtk/markermaker.vala"
									_tmp105_ = g_strdup_printf ("%c", string_get (_tmp104_, (glong) 0));
#line 102 "../src/gtk/markermaker.vala"
									_tmp106_ = _tmp105_;
#line 102 "../src/gtk/markermaker.vala"
									_tmp107_ = g_strcmp0 (_tmp106_, "5") == 0;
#line 102 "../src/gtk/markermaker.vala"
									_g_free0 (_tmp106_);
#line 102 "../src/gtk/markermaker.vala"
									if (_tmp107_) {
#line 1082 "markermaker.c"
										const gchar* _tmp108_;
										gint _tmp109_;
										gint _tmp110_;
#line 102 "../src/gtk/markermaker.vala"
										_tmp108_ = _data1_->routeInfo;
#line 102 "../src/gtk/markermaker.vala"
										_tmp109_ = strlen (_tmp108_);
#line 102 "../src/gtk/markermaker.vala"
										_tmp110_ = _tmp109_;
#line 102 "../src/gtk/markermaker.vala"
										_tmp103_ = _tmp110_ == 3;
#line 1094 "markermaker.c"
									} else {
#line 102 "../src/gtk/markermaker.vala"
										_tmp103_ = FALSE;
#line 1098 "markermaker.c"
									}
#line 102 "../src/gtk/markermaker.vala"
									if (_tmp103_) {
#line 1102 "markermaker.c"
										GtkImage* _tmp111_;
										gchar* _tmp112_;
#line 103 "../src/gtk/markermaker.vala"
										_tmp111_ = image;
#line 103 "../src/gtk/markermaker.vala"
										gtk_widget_add_css_class ((GtkWidget*) _tmp111_, "Express");
#line 104 "../src/gtk/markermaker.vala"
										_tmp112_ = g_strdup ("Express Route");
#line 104 "../src/gtk/markermaker.vala"
										_g_free0 (_data1_->routeType);
#line 104 "../src/gtk/markermaker.vala"
										_data1_->routeType = _tmp112_;
#line 1115 "markermaker.c"
									} else {
										GtkImage* _tmp113_;
										gchar* _tmp114_;
#line 109 "../src/gtk/markermaker.vala"
										_tmp113_ = image;
#line 109 "../src/gtk/markermaker.vala"
										gtk_widget_add_css_class ((GtkWidget*) _tmp113_, "Metro");
#line 110 "../src/gtk/markermaker.vala"
										_tmp114_ = g_strdup ("Metro Bus");
#line 110 "../src/gtk/markermaker.vala"
										_g_free0 (_data1_->routeType);
#line 110 "../src/gtk/markermaker.vala"
										_data1_->routeType = _tmp114_;
#line 1129 "markermaker.c"
									}
								}
#line 113 "../src/gtk/markermaker.vala"
								_tmp115_ = route_object;
#line 113 "../src/gtk/markermaker.vala"
								_tmp116_ = json_object_get_string_member (_tmp115_, "route_desc");
#line 113 "../src/gtk/markermaker.vala"
								_tmp117_ = g_strdup (_tmp116_);
#line 113 "../src/gtk/markermaker.vala"
								_g_free0 (_data1_->routeDescription);
#line 113 "../src/gtk/markermaker.vala"
								_data1_->routeDescription = _tmp117_;
#line 1142 "markermaker.c"
							}
#line 93 "../src/gtk/markermaker.vala"
							_json_object_unref0 (route_object);
#line 1146 "markermaker.c"
						}
					}
				}
#line 119 "../src/gtk/markermaker.vala"
				_tmp118_ = (GtkGestureClick*) gtk_gesture_click_new ();
#line 119 "../src/gtk/markermaker.vala"
				gesture = _tmp118_;
#line 121 "../src/gtk/markermaker.vala"
				_tmp119_ = _data1_->marker;
#line 121 "../src/gtk/markermaker.vala"
				_tmp120_ = gesture;
#line 121 "../src/gtk/markermaker.vala"
				_tmp121_ = _g_object_ref0 ((GtkEventController*) _tmp120_);
#line 121 "../src/gtk/markermaker.vala"
				gtk_widget_add_controller ((GtkWidget*) _tmp119_, _tmp121_);
#line 124 "../src/gtk/markermaker.vala"
				_tmp122_ = gesture;
#line 124 "../src/gtk/markermaker.vala"
				g_signal_connect_data (_tmp122_, "pressed", (GCallback) ______lambda4__gtk_gesture_click_pressed, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 165 "../src/gtk/markermaker.vala"
				_tmp123_ = jsonBuilder;
#line 165 "../src/gtk/markermaker.vala"
				_tmp124_ = _data1_->routeInfo;
#line 165 "../src/gtk/markermaker.vala"
				json_builder_set_member_name (_tmp123_, _tmp124_);
#line 166 "../src/gtk/markermaker.vala"
				_tmp125_ = jsonBuilder;
#line 166 "../src/gtk/markermaker.vala"
				json_builder_begin_object (_tmp125_);
#line 167 "../src/gtk/markermaker.vala"
				_tmp126_ = jsonBuilder;
#line 167 "../src/gtk/markermaker.vala"
				_tmp127_ = tripID;
#line 167 "../src/gtk/markermaker.vala"
				json_builder_set_member_name (_tmp126_, _tmp127_);
#line 168 "../src/gtk/markermaker.vala"
				_tmp128_ = jsonBuilder;
#line 168 "../src/gtk/markermaker.vala"
				json_builder_begin_object (_tmp128_);
#line 169 "../src/gtk/markermaker.vala"
				_tmp129_ = jsonBuilder;
#line 169 "../src/gtk/markermaker.vala"
				json_builder_set_member_name (_tmp129_, "latitude");
#line 170 "../src/gtk/markermaker.vala"
				_tmp130_ = jsonBuilder;
#line 170 "../src/gtk/markermaker.vala"
				json_builder_add_double_value (_tmp130_, latitude);
#line 171 "../src/gtk/markermaker.vala"
				_tmp131_ = jsonBuilder;
#line 171 "../src/gtk/markermaker.vala"
				json_builder_set_member_name (_tmp131_, "longitude");
#line 172 "../src/gtk/markermaker.vala"
				_tmp132_ = jsonBuilder;
#line 172 "../src/gtk/markermaker.vala"
				json_builder_add_double_value (_tmp132_, longitude);
#line 173 "../src/gtk/markermaker.vala"
				_tmp133_ = jsonBuilder;
#line 173 "../src/gtk/markermaker.vala"
				json_builder_end_object (_tmp133_);
#line 174 "../src/gtk/markermaker.vala"
				_tmp134_ = jsonBuilder;
#line 174 "../src/gtk/markermaker.vala"
				json_builder_end_object (_tmp134_);
#line 175 "../src/gtk/markermaker.vala"
				_tmp135_ = markerList;
#line 175 "../src/gtk/markermaker.vala"
				_tmp136_ = _data1_->marker;
#line 175 "../src/gtk/markermaker.vala"
				_tmp137_ = _g_object_ref0 (_tmp136_);
#line 175 "../src/gtk/markermaker.vala"
				g_array_append_val (_tmp135_, _tmp137_);
#line 41 "../src/gtk/markermaker.vala"
				_g_object_unref0 (gesture);
#line 41 "../src/gtk/markermaker.vala"
				_json_array_unref0 (root_array);
#line 41 "../src/gtk/markermaker.vala"
				_g_object_unref0 (image);
#line 41 "../src/gtk/markermaker.vala"
				_g_free0 (routeID);
#line 41 "../src/gtk/markermaker.vala"
				_g_free0 (tripID);
#line 41 "../src/gtk/markermaker.vala"
				_json_object_unref0 (tripObject);
#line 41 "../src/gtk/markermaker.vala"
				__vala_JsonNode_free0 (tripNode);
#line 41 "../src/gtk/markermaker.vala"
				_json_object_unref0 (innerVehicleObject);
#line 41 "../src/gtk/markermaker.vala"
				__vala_JsonNode_free0 (innerVehicleNode);
#line 41 "../src/gtk/markermaker.vala"
				_json_object_unref0 (outerVehicleObject);
#line 41 "../src/gtk/markermaker.vala"
				__vala_JsonNode_free0 (outerVehicleNode);
#line 41 "../src/gtk/markermaker.vala"
				_g_free0 (id);
#line 41 "../src/gtk/markermaker.vala"
				_json_object_unref0 (entityObject);
#line 41 "../src/gtk/markermaker.vala"
				__vala_JsonNode_free0 (entityPostition);
#line 41 "../src/gtk/markermaker.vala"
				block1_data_unref (_data1_);
#line 41 "../src/gtk/markermaker.vala"
				_data1_ = NULL;
#line 1250 "markermaker.c"
			}
		}
	}
#line 178 "../src/gtk/markermaker.vala"
	result = markerList;
#line 178 "../src/gtk/markermaker.vala"
	__vala_JsonNode_free0 (localNode);
#line 178 "../src/gtk/markermaker.vala"
	_g_object_unref0 (jsonBuilder);
#line 178 "../src/gtk/markermaker.vala"
	_g_bytes_unref0 (resource);
#line 178 "../src/gtk/markermaker.vala"
	_g_free0 (resource_path);
#line 178 "../src/gtk/markermaker.vala"
	_g_object_unref0 (localParser);
#line 178 "../src/gtk/markermaker.vala"
	_json_array_unref0 (entityArray);
#line 178 "../src/gtk/markermaker.vala"
	_json_object_unref0 (object);
#line 178 "../src/gtk/markermaker.vala"
	__vala_JsonNode_free0 (node);
#line 178 "../src/gtk/markermaker.vala"
	_g_object_unref0 (parser);
#line 178 "../src/gtk/markermaker.vala"
	_g_object_unref0 (response);
#line 178 "../src/gtk/markermaker.vala"
	_g_object_unref0 (message);
#line 178 "../src/gtk/markermaker.vala"
	_g_object_unref0 (session);
#line 178 "../src/gtk/markermaker.vala"
	_g_free0 (kcjsonurl);
#line 178 "../src/gtk/markermaker.vala"
	return result;
#line 1284 "markermaker.c"
}

KctrackerMarkermaker*
kctracker_markermaker_construct (GType object_type)
{
	KctrackerMarkermaker* self = NULL;
#line 7 "../src/gtk/markermaker.vala"
	self = (KctrackerMarkermaker*) g_type_create_instance (object_type);
#line 7 "../src/gtk/markermaker.vala"
	return self;
#line 1295 "markermaker.c"
}

KctrackerMarkermaker*
kctracker_markermaker_new (void)
{
#line 7 "../src/gtk/markermaker.vala"
	return kctracker_markermaker_construct (KCTRACKER_TYPE_MARKERMAKER);
#line 1303 "markermaker.c"
}

static void
kctracker_value_markermaker_init (GValue* value)
{
#line 7 "../src/gtk/markermaker.vala"
	value->data[0].v_pointer = NULL;
#line 1311 "markermaker.c"
}

static void
kctracker_value_markermaker_free_value (GValue* value)
{
#line 7 "../src/gtk/markermaker.vala"
	if (value->data[0].v_pointer) {
#line 7 "../src/gtk/markermaker.vala"
		kctracker_markermaker_unref (value->data[0].v_pointer);
#line 1321 "markermaker.c"
	}
}

static void
kctracker_value_markermaker_copy_value (const GValue* src_value,
                                        GValue* dest_value)
{
#line 7 "../src/gtk/markermaker.vala"
	if (src_value->data[0].v_pointer) {
#line 7 "../src/gtk/markermaker.vala"
		dest_value->data[0].v_pointer = kctracker_markermaker_ref (src_value->data[0].v_pointer);
#line 1333 "markermaker.c"
	} else {
#line 7 "../src/gtk/markermaker.vala"
		dest_value->data[0].v_pointer = NULL;
#line 1337 "markermaker.c"
	}
}

static gpointer
kctracker_value_markermaker_peek_pointer (const GValue* value)
{
#line 7 "../src/gtk/markermaker.vala"
	return value->data[0].v_pointer;
#line 1346 "markermaker.c"
}

static gchar*
kctracker_value_markermaker_collect_value (GValue* value,
                                           guint n_collect_values,
                                           GTypeCValue* collect_values,
                                           guint collect_flags)
{
#line 7 "../src/gtk/markermaker.vala"
	if (collect_values[0].v_pointer) {
#line 1357 "markermaker.c"
		KctrackerMarkermaker * object;
		object = collect_values[0].v_pointer;
#line 7 "../src/gtk/markermaker.vala"
		if (object->parent_instance.g_class == NULL) {
#line 7 "../src/gtk/markermaker.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 1364 "markermaker.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 7 "../src/gtk/markermaker.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 1368 "markermaker.c"
		}
#line 7 "../src/gtk/markermaker.vala"
		value->data[0].v_pointer = kctracker_markermaker_ref (object);
#line 1372 "markermaker.c"
	} else {
#line 7 "../src/gtk/markermaker.vala"
		value->data[0].v_pointer = NULL;
#line 1376 "markermaker.c"
	}
#line 7 "../src/gtk/markermaker.vala"
	return NULL;
#line 1380 "markermaker.c"
}

static gchar*
kctracker_value_markermaker_lcopy_value (const GValue* value,
                                         guint n_collect_values,
                                         GTypeCValue* collect_values,
                                         guint collect_flags)
{
	KctrackerMarkermaker ** object_p;
	object_p = collect_values[0].v_pointer;
#line 7 "../src/gtk/markermaker.vala"
	if (!object_p) {
#line 7 "../src/gtk/markermaker.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 1395 "markermaker.c"
	}
#line 7 "../src/gtk/markermaker.vala"
	if (!value->data[0].v_pointer) {
#line 7 "../src/gtk/markermaker.vala"
		*object_p = NULL;
#line 1401 "markermaker.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 7 "../src/gtk/markermaker.vala"
		*object_p = value->data[0].v_pointer;
#line 1405 "markermaker.c"
	} else {
#line 7 "../src/gtk/markermaker.vala"
		*object_p = kctracker_markermaker_ref (value->data[0].v_pointer);
#line 1409 "markermaker.c"
	}
#line 7 "../src/gtk/markermaker.vala"
	return NULL;
#line 1413 "markermaker.c"
}

GParamSpec*
kctracker_param_spec_markermaker (const gchar* name,
                                  const gchar* nick,
                                  const gchar* blurb,
                                  GType object_type,
                                  GParamFlags flags)
{
	KctrackerParamSpecMarkermaker* spec;
#line 7 "../src/gtk/markermaker.vala"
	g_return_val_if_fail (g_type_is_a (object_type, KCTRACKER_TYPE_MARKERMAKER), NULL);
#line 7 "../src/gtk/markermaker.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 7 "../src/gtk/markermaker.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 7 "../src/gtk/markermaker.vala"
	return G_PARAM_SPEC (spec);
#line 1432 "markermaker.c"
}

gpointer
kctracker_value_get_markermaker (const GValue* value)
{
#line 7 "../src/gtk/markermaker.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, KCTRACKER_TYPE_MARKERMAKER), NULL);
#line 7 "../src/gtk/markermaker.vala"
	return value->data[0].v_pointer;
#line 1442 "markermaker.c"
}

void
kctracker_value_set_markermaker (GValue* value,
                                 gpointer v_object)
{
	KctrackerMarkermaker * old;
#line 7 "../src/gtk/markermaker.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, KCTRACKER_TYPE_MARKERMAKER));
#line 7 "../src/gtk/markermaker.vala"
	old = value->data[0].v_pointer;
#line 7 "../src/gtk/markermaker.vala"
	if (v_object) {
#line 7 "../src/gtk/markermaker.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, KCTRACKER_TYPE_MARKERMAKER));
#line 7 "../src/gtk/markermaker.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 7 "../src/gtk/markermaker.vala"
		value->data[0].v_pointer = v_object;
#line 7 "../src/gtk/markermaker.vala"
		kctracker_markermaker_ref (value->data[0].v_pointer);
#line 1464 "markermaker.c"
	} else {
#line 7 "../src/gtk/markermaker.vala"
		value->data[0].v_pointer = NULL;
#line 1468 "markermaker.c"
	}
#line 7 "../src/gtk/markermaker.vala"
	if (old) {
#line 7 "../src/gtk/markermaker.vala"
		kctracker_markermaker_unref (old);
#line 1474 "markermaker.c"
	}
}

void
kctracker_value_take_markermaker (GValue* value,
                                  gpointer v_object)
{
	KctrackerMarkermaker * old;
#line 7 "../src/gtk/markermaker.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, KCTRACKER_TYPE_MARKERMAKER));
#line 7 "../src/gtk/markermaker.vala"
	old = value->data[0].v_pointer;
#line 7 "../src/gtk/markermaker.vala"
	if (v_object) {
#line 7 "../src/gtk/markermaker.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, KCTRACKER_TYPE_MARKERMAKER));
#line 7 "../src/gtk/markermaker.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 7 "../src/gtk/markermaker.vala"
		value->data[0].v_pointer = v_object;
#line 1495 "markermaker.c"
	} else {
#line 7 "../src/gtk/markermaker.vala"
		value->data[0].v_pointer = NULL;
#line 1499 "markermaker.c"
	}
#line 7 "../src/gtk/markermaker.vala"
	if (old) {
#line 7 "../src/gtk/markermaker.vala"
		kctracker_markermaker_unref (old);
#line 1505 "markermaker.c"
	}
}

static void
kctracker_markermaker_class_init (KctrackerMarkermakerClass * klass,
                                  gpointer klass_data)
{
#line 7 "../src/gtk/markermaker.vala"
	kctracker_markermaker_parent_class = g_type_class_peek_parent (klass);
#line 7 "../src/gtk/markermaker.vala"
	((KctrackerMarkermakerClass *) klass)->finalize = kctracker_markermaker_finalize;
#line 1517 "markermaker.c"
}

static void
kctracker_markermaker_instance_init (KctrackerMarkermaker * self,
                                     gpointer klass)
{
#line 7 "../src/gtk/markermaker.vala"
	self->ref_count = 1;
#line 1526 "markermaker.c"
}

static void
kctracker_markermaker_finalize (KctrackerMarkermaker * obj)
{
	KctrackerMarkermaker * self;
#line 7 "../src/gtk/markermaker.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, KCTRACKER_TYPE_MARKERMAKER, KctrackerMarkermaker);
#line 7 "../src/gtk/markermaker.vala"
	g_signal_handlers_destroy (self);
#line 1537 "markermaker.c"
}

static GType
kctracker_markermaker_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { kctracker_value_markermaker_init, kctracker_value_markermaker_free_value, kctracker_value_markermaker_copy_value, kctracker_value_markermaker_peek_pointer, "p", kctracker_value_markermaker_collect_value, "p", kctracker_value_markermaker_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (KctrackerMarkermakerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) kctracker_markermaker_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (KctrackerMarkermaker), 0, (GInstanceInitFunc) kctracker_markermaker_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType kctracker_markermaker_type_id;
	kctracker_markermaker_type_id = g_type_register_fundamental (g_type_fundamental_next (), "KctrackerMarkermaker", &g_define_type_info, &g_define_type_fundamental_info, 0);
	return kctracker_markermaker_type_id;
}

GType
kctracker_markermaker_get_type (void)
{
	static volatile gsize kctracker_markermaker_type_id__once = 0;
	if (g_once_init_enter (&kctracker_markermaker_type_id__once)) {
		GType kctracker_markermaker_type_id;
		kctracker_markermaker_type_id = kctracker_markermaker_get_type_once ();
		g_once_init_leave (&kctracker_markermaker_type_id__once, kctracker_markermaker_type_id);
	}
	return kctracker_markermaker_type_id__once;
}

gpointer
kctracker_markermaker_ref (gpointer instance)
{
	KctrackerMarkermaker * self;
	self = instance;
#line 7 "../src/gtk/markermaker.vala"
	g_atomic_int_inc (&self->ref_count);
#line 7 "../src/gtk/markermaker.vala"
	return instance;
#line 1572 "markermaker.c"
}

void
kctracker_markermaker_unref (gpointer instance)
{
	KctrackerMarkermaker * self;
	self = instance;
#line 7 "../src/gtk/markermaker.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 7 "../src/gtk/markermaker.vala"
		KCTRACKER_MARKERMAKER_GET_CLASS (self)->finalize (self);
#line 7 "../src/gtk/markermaker.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 1586 "markermaker.c"
	}
}

