/* markers.c generated by valac 0.56.18, the Vala compiler
 * generated from markers.vala, do not modify */

#include <shumate/shumate.h>
#include <glib-object.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define KCTRACKER_TYPE_MARKERS (kctracker_markers_get_type ())
#define KCTRACKER_MARKERS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KCTRACKER_TYPE_MARKERS, KctrackerMarkers))
#define KCTRACKER_MARKERS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KCTRACKER_TYPE_MARKERS, KctrackerMarkersClass))
#define KCTRACKER_IS_MARKERS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KCTRACKER_TYPE_MARKERS))
#define KCTRACKER_IS_MARKERS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KCTRACKER_TYPE_MARKERS))
#define KCTRACKER_MARKERS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KCTRACKER_TYPE_MARKERS, KctrackerMarkersClass))

typedef struct _KctrackerMarkers KctrackerMarkers;
typedef struct _KctrackerMarkersClass KctrackerMarkersClass;
typedef struct _KctrackerMarkersPrivate KctrackerMarkersPrivate;
enum  {
	KCTRACKER_MARKERS_0_PROPERTY,
	KCTRACKER_MARKERS_NUM_PROPERTIES
};
static GParamSpec* kctracker_markers_properties[KCTRACKER_MARKERS_NUM_PROPERTIES];

struct _KctrackerMarkers {
	ShumateMarker parent_instance;
	KctrackerMarkersPrivate * priv;
};

struct _KctrackerMarkersClass {
	ShumateMarkerClass parent_class;
};

static gpointer kctracker_markers_parent_class = NULL;

VALA_EXTERN GType kctracker_markers_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KctrackerMarkers, g_object_unref)
VALA_EXTERN KctrackerMarkers* kctracker_markers_new (void);
VALA_EXTERN KctrackerMarkers* kctracker_markers_construct (GType object_type);
static GType kctracker_markers_get_type_once (void);

KctrackerMarkers*
kctracker_markers_construct (GType object_type)
{
	KctrackerMarkers * self = NULL;
#line 1 "../src/gtk/markers.vala"
	self = (KctrackerMarkers*) g_object_new (object_type, NULL);
#line 1 "../src/gtk/markers.vala"
	return self;
#line 67 "markers.c"
}

KctrackerMarkers*
kctracker_markers_new (void)
{
#line 1 "../src/gtk/markers.vala"
	return kctracker_markers_construct (KCTRACKER_TYPE_MARKERS);
#line 75 "markers.c"
}

static void
kctracker_markers_class_init (KctrackerMarkersClass * klass,
                              gpointer klass_data)
{
#line 1 "../src/gtk/markers.vala"
	kctracker_markers_parent_class = g_type_class_peek_parent (klass);
#line 84 "markers.c"
}

static void
kctracker_markers_instance_init (KctrackerMarkers * self,
                                 gpointer klass)
{
}

static GType
kctracker_markers_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (KctrackerMarkersClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) kctracker_markers_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (KctrackerMarkers), 0, (GInstanceInitFunc) kctracker_markers_instance_init, NULL };
	GType kctracker_markers_type_id;
	kctracker_markers_type_id = g_type_register_static (shumate_marker_get_type (), "KctrackerMarkers", &g_define_type_info, 0);
	return kctracker_markers_type_id;
}

GType
kctracker_markers_get_type (void)
{
	static volatile gsize kctracker_markers_type_id__once = 0;
	if (g_once_init_enter (&kctracker_markers_type_id__once)) {
		GType kctracker_markers_type_id;
		kctracker_markers_type_id = kctracker_markers_get_type_once ();
		g_once_init_leave (&kctracker_markers_type_id__once, kctracker_markers_type_id);
	}
	return kctracker_markers_type_id__once;
}

