/* application.c generated by valac 0.56.18, the Vala compiler
 * generated from application.vala, do not modify */

#include <adwaita.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define KCTRACKER_TYPE_APPLICATION (kctracker_application_get_type ())
#define KCTRACKER_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KCTRACKER_TYPE_APPLICATION, KctrackerApplication))
#define KCTRACKER_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KCTRACKER_TYPE_APPLICATION, KctrackerApplicationClass))
#define KCTRACKER_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KCTRACKER_TYPE_APPLICATION))
#define KCTRACKER_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KCTRACKER_TYPE_APPLICATION))
#define KCTRACKER_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KCTRACKER_TYPE_APPLICATION, KctrackerApplicationClass))

typedef struct _KctrackerApplication KctrackerApplication;
typedef struct _KctrackerApplicationClass KctrackerApplicationClass;
typedef struct _KctrackerApplicationPrivate KctrackerApplicationPrivate;
enum  {
	KCTRACKER_APPLICATION_0_PROPERTY,
	KCTRACKER_APPLICATION_NUM_PROPERTIES
};
static GParamSpec* kctracker_application_properties[KCTRACKER_APPLICATION_NUM_PROPERTIES];

#define KCTRACKER_TYPE_WINDOW (kctracker_window_get_type ())
#define KCTRACKER_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KCTRACKER_TYPE_WINDOW, KctrackerWindow))
#define KCTRACKER_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KCTRACKER_TYPE_WINDOW, KctrackerWindowClass))
#define KCTRACKER_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KCTRACKER_TYPE_WINDOW))
#define KCTRACKER_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KCTRACKER_TYPE_WINDOW))
#define KCTRACKER_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KCTRACKER_TYPE_WINDOW, KctrackerWindowClass))

typedef struct _KctrackerWindow KctrackerWindow;
typedef struct _KctrackerWindowClass KctrackerWindowClass;

#define KCTRACKER_TYPE_MAPWIDGET (kctracker_mapwidget_get_type ())
#define KCTRACKER_MAPWIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KCTRACKER_TYPE_MAPWIDGET, KctrackerMapwidget))
#define KCTRACKER_MAPWIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KCTRACKER_TYPE_MAPWIDGET, KctrackerMapwidgetClass))
#define KCTRACKER_IS_MAPWIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KCTRACKER_TYPE_MAPWIDGET))
#define KCTRACKER_IS_MAPWIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KCTRACKER_TYPE_MAPWIDGET))
#define KCTRACKER_MAPWIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KCTRACKER_TYPE_MAPWIDGET, KctrackerMapwidgetClass))

typedef struct _KctrackerMapwidget KctrackerMapwidget;
typedef struct _KctrackerMapwidgetClass KctrackerMapwidgetClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef void (*GSimpleActionActivateCallback) (GSimpleAction* action, GVariant* parameter, gpointer user_data);

struct _KctrackerApplication {
	AdwApplication parent_instance;
	KctrackerApplicationPrivate * priv;
};

struct _KctrackerApplicationClass {
	AdwApplicationClass parent_class;
};

static gpointer kctracker_application_parent_class = NULL;

VALA_EXTERN GType kctracker_application_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KctrackerApplication, g_object_unref)
VALA_EXTERN KctrackerApplication* kctracker_application_new (void);
VALA_EXTERN KctrackerApplication* kctracker_application_construct (GType object_type);
static void kctracker_application_real_activate (GApplication* base);
VALA_EXTERN GType kctracker_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KctrackerWindow, g_object_unref)
VALA_EXTERN KctrackerWindow* kctracker_window_new (GtkApplication* app);
VALA_EXTERN KctrackerWindow* kctracker_window_construct (GType object_type,
                                             GtkApplication* app);
VALA_EXTERN GType kctracker_mapwidget_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KctrackerMapwidget, g_object_unref)
VALA_EXTERN KctrackerMapwidget* kctracker_mapwidget_new (void);
VALA_EXTERN KctrackerMapwidget* kctracker_mapwidget_construct (GType object_type);
static void kctracker_application_on_about_action (KctrackerApplication* self);
static gchar** _vala_array_dup1 (gchar** self,
                          gssize length);
static void kctracker_application_on_preferences_action (KctrackerApplication* self);
static void kctracker_application_refresh (KctrackerApplication* self);
static GObject * kctracker_application_constructor (GType type,
                                             guint n_construct_properties,
                                             GObjectConstructParam * construct_properties);
static void _kctracker_application_on_about_action_gsimple_action_activate_callback (GSimpleAction* action,
                                                                              GVariant* parameter,
                                                                              gpointer self);
static void _kctracker_application_on_preferences_action_gsimple_action_activate_callback (GSimpleAction* action,
                                                                                    GVariant* parameter,
                                                                                    gpointer self);
static void _kctracker_application_refresh_gsimple_action_activate_callback (GSimpleAction* action,
                                                                      GVariant* parameter,
                                                                      gpointer self);
static void _g_application_quit_gsimple_action_activate_callback (GSimpleAction* action,
                                                           GVariant* parameter,
                                                           gpointer self);
static GType kctracker_application_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);

KctrackerApplication*
kctracker_application_construct (GType object_type)
{
	KctrackerApplication * self = NULL;
#line 5 "../src/application.vala"
	self = (KctrackerApplication*) g_object_new (object_type, "application-id", "me.flagmaster.kctracker", "flags", G_APPLICATION_DEFAULT_FLAGS, NULL);
#line 4 "../src/application.vala"
	return self;
#line 133 "application.c"
}

KctrackerApplication*
kctracker_application_new (void)
{
#line 4 "../src/application.vala"
	return kctracker_application_construct (KCTRACKER_TYPE_APPLICATION);
#line 141 "application.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 39 "../src/application.vala"
	return self ? g_object_ref (self) : NULL;
#line 149 "application.c"
}

static void
kctracker_application_real_activate (GApplication* base)
{
	KctrackerApplication * self;
	KctrackerWindow* win = NULL;
	KctrackerWindow* _tmp0_;
	KctrackerMapwidget* map = NULL;
	KctrackerMapwidget* _tmp1_;
	GtkCssProvider* css_provider = NULL;
	GtkCssProvider* _tmp2_;
	GdkDisplay* _tmp3_;
	AdwToolbarView* adwToolbarView = NULL;
	GtkWidget* _tmp4_;
	AdwToolbarView* _tmp5_;
#line 24 "../src/application.vala"
	self = (KctrackerApplication*) base;
#line 25 "../src/application.vala"
	G_APPLICATION_CLASS (kctracker_application_parent_class)->activate ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, adw_application_get_type (), AdwApplication));
#line 26 "../src/application.vala"
	_tmp0_ = kctracker_window_new ((GtkApplication*) self);
#line 26 "../src/application.vala"
	g_object_ref_sink (_tmp0_);
#line 26 "../src/application.vala"
	win = _tmp0_;
#line 27 "../src/application.vala"
	_tmp1_ = kctracker_mapwidget_new ();
#line 27 "../src/application.vala"
	g_object_ref_sink (_tmp1_);
#line 27 "../src/application.vala"
	map = _tmp1_;
#line 31 "../src/application.vala"
	_tmp2_ = gtk_css_provider_new ();
#line 31 "../src/application.vala"
	css_provider = _tmp2_;
#line 32 "../src/application.vala"
	gtk_css_provider_load_from_resource (css_provider, "/me/flagmaster/kctracker/iconColours.css");
#line 33 "../src/application.vala"
	_tmp3_ = gdk_display_get_default ();
#line 33 "../src/application.vala"
	gtk_style_context_add_provider_for_display (_tmp3_, (GtkStyleProvider*) css_provider, (guint) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
#line 39 "../src/application.vala"
	_tmp4_ = adw_application_window_get_content ((AdwApplicationWindow*) win);
#line 39 "../src/application.vala"
	_tmp5_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp4_, adw_toolbar_view_get_type ()) ? ((AdwToolbarView*) _tmp4_) : NULL);
#line 39 "../src/application.vala"
	adwToolbarView = _tmp5_;
#line 41 "../src/application.vala"
	adw_toolbar_view_set_content (adwToolbarView, (GtkWidget*) map);
#line 43 "../src/application.vala"
	gtk_window_present ((GtkWindow*) win);
#line 24 "../src/application.vala"
	_g_object_unref0 (adwToolbarView);
#line 24 "../src/application.vala"
	_g_object_unref0 (css_provider);
#line 24 "../src/application.vala"
	_g_object_unref0 (map);
#line 24 "../src/application.vala"
	_g_object_unref0 (win);
#line 210 "application.c"
}

static gchar**
_vala_array_dup1 (gchar** self,
                  gssize length)
{
#line 49 "../src/application.vala"
	if (length >= 0) {
#line 219 "application.c"
		gchar** result;
		gssize i;
#line 49 "../src/application.vala"
		result = g_new0 (gchar*, length + 1);
#line 49 "../src/application.vala"
		for (i = 0; i < length; i++) {
#line 226 "application.c"
			gchar* _tmp0_;
#line 49 "../src/application.vala"
			_tmp0_ = g_strdup (self[i]);
#line 49 "../src/application.vala"
			result[i] = _tmp0_;
#line 232 "application.c"
		}
#line 49 "../src/application.vala"
		return result;
#line 236 "application.c"
	}
#line 49 "../src/application.vala"
	return NULL;
#line 240 "application.c"
}

static void
kctracker_application_on_about_action (KctrackerApplication* self)
{
	gchar** developers = NULL;
	gchar* _tmp0_;
	gchar** _tmp1_;
	gint developers_length1;
	gint _developers_size_;
	AdwAboutDialog* about = NULL;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar** _tmp7_;
	gint _tmp7__length1;
	gchar* _tmp8_;
	AdwAboutDialog* _tmp9_ = NULL;
	GtkWindow* _tmp10_;
	GtkWindow* _tmp11_;
#line 47 "../src/application.vala"
	g_return_if_fail (self != NULL);
#line 48 "../src/application.vala"
	_tmp0_ = g_strdup ("Flagmaster");
#line 48 "../src/application.vala"
	_tmp1_ = g_new0 (gchar*, 1 + 1);
#line 48 "../src/application.vala"
	_tmp1_[0] = _tmp0_;
#line 48 "../src/application.vala"
	developers = _tmp1_;
#line 48 "../src/application.vala"
	developers_length1 = 1;
#line 48 "../src/application.vala"
	_developers_size_ = developers_length1;
#line 49 "../src/application.vala"
	_tmp2_ = g_strdup ("kctracker");
#line 49 "../src/application.vala"
	_tmp3_ = g_strdup ("me.flagmaster.kctracker");
#line 49 "../src/application.vala"
	_tmp4_ = g_strdup ("Flagmaster");
#line 49 "../src/application.vala"
	_tmp5_ = g_strdup (_ ("translator-credits"));
#line 49 "../src/application.vala"
	_tmp6_ = g_strdup ("1.0.1");
#line 49 "../src/application.vala"
	_tmp7_ = (developers != NULL) ? _vala_array_dup1 (developers, developers_length1) : developers;
#line 49 "../src/application.vala"
	_tmp7__length1 = developers_length1;
#line 49 "../src/application.vala"
	_tmp8_ = g_strdup ("Mozilla Public License Version 2.0");
#line 49 "../src/application.vala"
	_tmp9_ = (AdwAboutDialog*) adw_about_dialog_new ();
#line 49 "../src/application.vala"
	adw_about_dialog_set_application_name (_tmp9_, _tmp2_);
#line 49 "../src/application.vala"
	_g_free0 (_tmp2_);
#line 49 "../src/application.vala"
	adw_about_dialog_set_application_icon (_tmp9_, _tmp3_);
#line 49 "../src/application.vala"
	_g_free0 (_tmp3_);
#line 49 "../src/application.vala"
	adw_about_dialog_set_developer_name (_tmp9_, _tmp4_);
#line 49 "../src/application.vala"
	_g_free0 (_tmp4_);
#line 49 "../src/application.vala"
	adw_about_dialog_set_translator_credits (_tmp9_, _tmp5_);
#line 49 "../src/application.vala"
	_g_free0 (_tmp5_);
#line 49 "../src/application.vala"
	adw_about_dialog_set_version (_tmp9_, _tmp6_);
#line 49 "../src/application.vala"
	_g_free0 (_tmp6_);
#line 49 "../src/application.vala"
	adw_about_dialog_set_developers (_tmp9_, _tmp7_);
#line 49 "../src/application.vala"
	_tmp7_ = (_vala_array_free (_tmp7_, _tmp7__length1, (GDestroyNotify) g_free), NULL);
#line 49 "../src/application.vala"
	adw_about_dialog_set_copyright (_tmp9_, _tmp8_);
#line 49 "../src/application.vala"
	_g_free0 (_tmp8_);
#line 49 "../src/application.vala"
	g_object_ref_sink (_tmp9_);
#line 49 "../src/application.vala"
	about = _tmp9_;
#line 59 "../src/application.vala"
	_tmp10_ = gtk_application_get_active_window ((GtkApplication*) self);
#line 59 "../src/application.vala"
	_tmp11_ = _tmp10_;
#line 59 "../src/application.vala"
	adw_dialog_present ((AdwDialog*) about, (GtkWidget*) _tmp11_);
#line 47 "../src/application.vala"
	_g_object_unref0 (about);
#line 47 "../src/application.vala"
	developers = (_vala_array_free (developers, developers_length1, (GDestroyNotify) g_free), NULL);
#line 337 "application.c"
}

static void
kctracker_application_on_preferences_action (KctrackerApplication* self)
{
#line 62 "../src/application.vala"
	g_return_if_fail (self != NULL);
#line 345 "application.c"
}

static void
kctracker_application_refresh (KctrackerApplication* self)
{
	KctrackerWindow* win = NULL;
	GtkWindow* _tmp0_;
	GtkWindow* _tmp1_;
	KctrackerWindow* _tmp2_;
	KctrackerMapwidget* map = NULL;
	KctrackerMapwidget* _tmp3_;
	AdwToolbarView* adwToolbarView = NULL;
	GtkWidget* _tmp4_;
	AdwToolbarView* _tmp5_;
#line 67 "../src/application.vala"
	g_return_if_fail (self != NULL);
#line 68 "../src/application.vala"
	_tmp0_ = gtk_application_get_active_window ((GtkApplication*) self);
#line 68 "../src/application.vala"
	_tmp1_ = _tmp0_;
#line 68 "../src/application.vala"
	_tmp2_ = _g_object_ref0 (KCTRACKER_IS_WINDOW (_tmp1_) ? ((KctrackerWindow*) _tmp1_) : NULL);
#line 68 "../src/application.vala"
	win = _tmp2_;
#line 69 "../src/application.vala"
	_tmp3_ = kctracker_mapwidget_new ();
#line 69 "../src/application.vala"
	g_object_ref_sink (_tmp3_);
#line 69 "../src/application.vala"
	map = _tmp3_;
#line 71 "../src/application.vala"
	_tmp4_ = adw_application_window_get_content ((AdwApplicationWindow*) win);
#line 71 "../src/application.vala"
	_tmp5_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp4_, adw_toolbar_view_get_type ()) ? ((AdwToolbarView*) _tmp4_) : NULL);
#line 71 "../src/application.vala"
	adwToolbarView = _tmp5_;
#line 73 "../src/application.vala"
	adw_toolbar_view_set_content (adwToolbarView, (GtkWidget*) map);
#line 67 "../src/application.vala"
	_g_object_unref0 (adwToolbarView);
#line 67 "../src/application.vala"
	_g_object_unref0 (map);
#line 67 "../src/application.vala"
	_g_object_unref0 (win);
#line 390 "application.c"
}

static void
_kctracker_application_on_about_action_gsimple_action_activate_callback (GSimpleAction* action,
                                                                         GVariant* parameter,
                                                                         gpointer self)
{
#line 12 "../src/application.vala"
	kctracker_application_on_about_action ((KctrackerApplication*) self);
#line 400 "application.c"
}

static void
_kctracker_application_on_preferences_action_gsimple_action_activate_callback (GSimpleAction* action,
                                                                               GVariant* parameter,
                                                                               gpointer self)
{
#line 12 "../src/application.vala"
	kctracker_application_on_preferences_action ((KctrackerApplication*) self);
#line 410 "application.c"
}

static void
_kctracker_application_refresh_gsimple_action_activate_callback (GSimpleAction* action,
                                                                 GVariant* parameter,
                                                                 gpointer self)
{
#line 12 "../src/application.vala"
	kctracker_application_refresh ((KctrackerApplication*) self);
#line 420 "application.c"
}

static void
_g_application_quit_gsimple_action_activate_callback (GSimpleAction* action,
                                                      GVariant* parameter,
                                                      gpointer self)
{
#line 12 "../src/application.vala"
	g_application_quit ((GApplication*) self);
#line 430 "application.c"
}

static GObject *
kctracker_application_constructor (GType type,
                                   guint n_construct_properties,
                                   GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	KctrackerApplication * self;
	GActionEntry* action_entries = NULL;
	GActionEntry _tmp0_ = {0};
	GActionEntry _tmp1_ = {0};
	GActionEntry _tmp2_ = {0};
	GActionEntry _tmp3_ = {0};
	GActionEntry* _tmp4_;
	gint action_entries_length1;
	gint _action_entries_size_;
	GActionEntry* _tmp5_;
	gint _tmp5__length1;
	gchar* _tmp6_;
	gchar** _tmp7_;
	gchar** _tmp8_;
	gint _tmp8__length1;
	gchar* _tmp9_;
	gchar** _tmp10_;
	gchar** _tmp11_;
	gint _tmp11__length1;
#line 11 "../src/application.vala"
	parent_class = G_OBJECT_CLASS (kctracker_application_parent_class);
#line 11 "../src/application.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 11 "../src/application.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, KCTRACKER_TYPE_APPLICATION, KctrackerApplication);
#line 12 "../src/application.vala"
	memset (&_tmp0_, 0, sizeof (GActionEntry));
#line 12 "../src/application.vala"
	_tmp0_.name = "about";
#line 12 "../src/application.vala"
	_tmp0_.activate = _kctracker_application_on_about_action_gsimple_action_activate_callback;
#line 12 "../src/application.vala"
	memset (&_tmp1_, 0, sizeof (GActionEntry));
#line 12 "../src/application.vala"
	_tmp1_.name = "preferences";
#line 12 "../src/application.vala"
	_tmp1_.activate = _kctracker_application_on_preferences_action_gsimple_action_activate_callback;
#line 12 "../src/application.vala"
	memset (&_tmp2_, 0, sizeof (GActionEntry));
#line 12 "../src/application.vala"
	_tmp2_.name = "refresh";
#line 12 "../src/application.vala"
	_tmp2_.activate = _kctracker_application_refresh_gsimple_action_activate_callback;
#line 12 "../src/application.vala"
	memset (&_tmp3_, 0, sizeof (GActionEntry));
#line 12 "../src/application.vala"
	_tmp3_.name = "quit";
#line 12 "../src/application.vala"
	_tmp3_.activate = _g_application_quit_gsimple_action_activate_callback;
#line 12 "../src/application.vala"
	_tmp4_ = g_new0 (GActionEntry, 4);
#line 12 "../src/application.vala"
	_tmp4_[0] = _tmp0_;
#line 12 "../src/application.vala"
	_tmp4_[1] = _tmp1_;
#line 12 "../src/application.vala"
	_tmp4_[2] = _tmp2_;
#line 12 "../src/application.vala"
	_tmp4_[3] = _tmp3_;
#line 12 "../src/application.vala"
	action_entries = _tmp4_;
#line 12 "../src/application.vala"
	action_entries_length1 = 4;
#line 12 "../src/application.vala"
	_action_entries_size_ = action_entries_length1;
#line 18 "../src/application.vala"
	_tmp5_ = action_entries;
#line 18 "../src/application.vala"
	_tmp5__length1 = action_entries_length1;
#line 18 "../src/application.vala"
	g_action_map_add_action_entries ((GActionMap*) self, _tmp5_, (gint) _tmp5__length1, self);
#line 19 "../src/application.vala"
	_tmp6_ = g_strdup ("<primary>q");
#line 19 "../src/application.vala"
	_tmp7_ = g_new0 (gchar*, 1 + 1);
#line 19 "../src/application.vala"
	_tmp7_[0] = _tmp6_;
#line 19 "../src/application.vala"
	_tmp8_ = _tmp7_;
#line 19 "../src/application.vala"
	_tmp8__length1 = 1;
#line 19 "../src/application.vala"
	gtk_application_set_accels_for_action ((GtkApplication*) self, "app.quit", _tmp8_);
#line 19 "../src/application.vala"
	_tmp8_ = (_vala_array_free (_tmp8_, _tmp8__length1, (GDestroyNotify) g_free), NULL);
#line 20 "../src/application.vala"
	_tmp9_ = g_strdup ("<primary>r");
#line 20 "../src/application.vala"
	_tmp10_ = g_new0 (gchar*, 1 + 1);
#line 20 "../src/application.vala"
	_tmp10_[0] = _tmp9_;
#line 20 "../src/application.vala"
	_tmp11_ = _tmp10_;
#line 20 "../src/application.vala"
	_tmp11__length1 = 1;
#line 20 "../src/application.vala"
	gtk_application_set_accels_for_action ((GtkApplication*) self, "app.refresh", _tmp11_);
#line 20 "../src/application.vala"
	_tmp11_ = (_vala_array_free (_tmp11_, _tmp11__length1, (GDestroyNotify) g_free), NULL);
#line 11 "../src/application.vala"
	action_entries = (g_free (action_entries), NULL);
#line 11 "../src/application.vala"
	return obj;
#line 543 "application.c"
}

static void
kctracker_application_class_init (KctrackerApplicationClass * klass,
                                  gpointer klass_data)
{
#line 3 "../src/application.vala"
	kctracker_application_parent_class = g_type_class_peek_parent (klass);
#line 3 "../src/application.vala"
	((GApplicationClass *) klass)->activate = (void (*) (GApplication*)) kctracker_application_real_activate;
#line 3 "../src/application.vala"
	G_OBJECT_CLASS (klass)->constructor = kctracker_application_constructor;
#line 556 "application.c"
}

static void
kctracker_application_instance_init (KctrackerApplication * self,
                                     gpointer klass)
{
}

static GType
kctracker_application_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (KctrackerApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) kctracker_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (KctrackerApplication), 0, (GInstanceInitFunc) kctracker_application_instance_init, NULL };
	GType kctracker_application_type_id;
	kctracker_application_type_id = g_type_register_static (adw_application_get_type (), "KctrackerApplication", &g_define_type_info, 0);
	return kctracker_application_type_id;
}

GType
kctracker_application_get_type (void)
{
	static volatile gsize kctracker_application_type_id__once = 0;
	if (g_once_init_enter (&kctracker_application_type_id__once)) {
		GType kctracker_application_type_id;
		kctracker_application_type_id = kctracker_application_get_type_once ();
		g_once_init_leave (&kctracker_application_type_id__once, kctracker_application_type_id);
	}
	return kctracker_application_type_id__once;
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

