/* main.c generated by valac 0.56.18, the Vala compiler
 * generated from main.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib/gi18n-lib.h>
#include "config.h"
#include <adwaita.h>
#include <glib-object.h>
#include <gio/gio.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define KCTRACKER_TYPE_APPLICATION (kctracker_application_get_type ())
#define KCTRACKER_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KCTRACKER_TYPE_APPLICATION, KctrackerApplication))
#define KCTRACKER_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KCTRACKER_TYPE_APPLICATION, KctrackerApplicationClass))
#define KCTRACKER_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KCTRACKER_TYPE_APPLICATION))
#define KCTRACKER_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KCTRACKER_TYPE_APPLICATION))
#define KCTRACKER_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KCTRACKER_TYPE_APPLICATION, KctrackerApplicationClass))

typedef struct _KctrackerApplication KctrackerApplication;
typedef struct _KctrackerApplicationClass KctrackerApplicationClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

static gint _vala_main (gchar** args,
                 gint args_length1);
VALA_EXTERN GType kctracker_application_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KctrackerApplication, g_object_unref)
VALA_EXTERN KctrackerApplication* kctracker_application_new (void);
VALA_EXTERN KctrackerApplication* kctracker_application_construct (GType object_type);

static gint
_vala_main (gchar** args,
            gint args_length1)
{
	KctrackerApplication* app = NULL;
	KctrackerApplication* _tmp0_;
	gint result;
#line 4 "../src/main.vala"
	bindtextdomain (GETTEXT_PACKAGE, LOCALEDIR);
#line 5 "../src/main.vala"
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
#line 6 "../src/main.vala"
	textdomain (GETTEXT_PACKAGE);
#line 9 "../src/main.vala"
	_tmp0_ = kctracker_application_new ();
#line 9 "../src/main.vala"
	app = _tmp0_;
#line 11 "../src/main.vala"
	result = g_application_run ((GApplication*) app, (gint) args_length1, args);
#line 11 "../src/main.vala"
	_g_object_unref0 (app);
#line 11 "../src/main.vala"
	return result;
#line 73 "main.c"
}

int
main (int argc,
      char ** argv)
{
#line 3 "../src/main.vala"
	return _vala_main (argv, argc);
#line 82 "main.c"
}

