/* window.c generated by valac 0.56.18, the Vala compiler
 * generated from window.vala, do not modify */

#include <adwaita.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define KCTRACKER_TYPE_WINDOW (kctracker_window_get_type ())
#define KCTRACKER_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KCTRACKER_TYPE_WINDOW, KctrackerWindow))
#define KCTRACKER_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KCTRACKER_TYPE_WINDOW, KctrackerWindowClass))
#define KCTRACKER_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KCTRACKER_TYPE_WINDOW))
#define KCTRACKER_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KCTRACKER_TYPE_WINDOW))
#define KCTRACKER_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KCTRACKER_TYPE_WINDOW, KctrackerWindowClass))

typedef struct _KctrackerWindow KctrackerWindow;
typedef struct _KctrackerWindowClass KctrackerWindowClass;
typedef struct _KctrackerWindowPrivate KctrackerWindowPrivate;
enum  {
	KCTRACKER_WINDOW_0_PROPERTY,
	KCTRACKER_WINDOW_NUM_PROPERTIES
};
static GParamSpec* kctracker_window_properties[KCTRACKER_WINDOW_NUM_PROPERTIES];

struct _KctrackerWindow {
	AdwApplicationWindow parent_instance;
	KctrackerWindowPrivate * priv;
};

struct _KctrackerWindowClass {
	AdwApplicationWindowClass parent_class;
};

static gpointer kctracker_window_parent_class = NULL;

VALA_EXTERN GType kctracker_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (KctrackerWindow, g_object_unref)
VALA_EXTERN KctrackerWindow* kctracker_window_new (GtkApplication* app);
VALA_EXTERN KctrackerWindow* kctracker_window_construct (GType object_type,
                                             GtkApplication* app);
static GType kctracker_window_get_type_once (void);

KctrackerWindow*
kctracker_window_construct (GType object_type,
                            GtkApplication* app)
{
	KctrackerWindow * self = NULL;
#line 11 "../src/window.vala"
	g_return_val_if_fail (app != NULL, NULL);
#line 12 "../src/window.vala"
	self = (KctrackerWindow*) g_object_new (object_type, "application", app, NULL);
#line 11 "../src/window.vala"
	return self;
#line 73 "window.c"
}

KctrackerWindow*
kctracker_window_new (GtkApplication* app)
{
#line 11 "../src/window.vala"
	return kctracker_window_construct (KCTRACKER_TYPE_WINDOW, app);
#line 81 "window.c"
}

static void
kctracker_window_class_init (KctrackerWindowClass * klass,
                             gpointer klass_data)
{
#line 4 "../src/window.vala"
	kctracker_window_parent_class = g_type_class_peek_parent (klass);
#line 4 "../src/window.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/me/flagmaster/kctracker/window.ui");
#line 92 "window.c"
}

static void
kctracker_window_instance_init (KctrackerWindow * self,
                                gpointer klass)
{
#line 4 "../src/window.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 101 "window.c"
}

static GType
kctracker_window_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (KctrackerWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) kctracker_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (KctrackerWindow), 0, (GInstanceInitFunc) kctracker_window_instance_init, NULL };
	GType kctracker_window_type_id;
	kctracker_window_type_id = g_type_register_static (adw_application_window_get_type (), "KctrackerWindow", &g_define_type_info, 0);
	return kctracker_window_type_id;
}

GType
kctracker_window_get_type (void)
{
	static volatile gsize kctracker_window_type_id__once = 0;
	if (g_once_init_enter (&kctracker_window_type_id__once)) {
		GType kctracker_window_type_id;
		kctracker_window_type_id = kctracker_window_get_type_once ();
		g_once_init_leave (&kctracker_window_type_id__once, kctracker_window_type_id);
	}
	return kctracker_window_type_id__once;
}

