/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define GETTEXT_PACKAGE "kctracker"

#define LOCALEDIR "/app/share/locale"

#define PACKAGE_VERSION "0.1.0"

